### ISSUE TITLE
calling set() inside of dispose() creates an infinite loop?

### ISSUE THREAD

**Issue by tconroy** [isaacs/node-lru-cache#101]
Hey there, 

this may just be a case of me implementing this module incorrectly, but I'm running into an issue where I need to call `cache.set()` inside of the `dispose` handler, which seems to result in an endless `set -> dispose -> set -> dispose...` loop.

use case: I am caching a single API response from a server ( cache length === 1 ). When a user hits the route, they are served the cache.

If the cache is older than 1 hour, a new request should be made and stored into the cache, prior to serving the new value to the user. If this API request fails, the prior "stale" cache should be re-set for another hour, so that there is no data downtime. 

Here is my code...

```
const cache = lru({
  max: 1,
  maxAge: ONE_HOUR,
  stale: true,
  dispose: recache,
});

function recache(key = null, value = null) {
  let prevData;
  if (key && value) {
    prevData = value;
  } else if (cache.peek('data').length) {
    prevData = cache.peek('data');
  }
  return apiRequest(endpoint, { timeout: 5000 })
    .then(({ data }) => {
      // if we got back data, set them.
      if (data && data.length) {
        return Promise.resolve(cache.set('data', data));
      }
      // otherwise, return error
      return Promise.reject(reqError(500, 'No data returned from the API.'));
    })
    .catch((err) => {
      // something went wrong, re-set the old cache values.
      return Promise.resolve(cache.set('data', prevData));
    });
}

function checkCache() {
  if (cache.has('data')) {
    return Promise.resolve();
  }
  return recache();
}

router.get('/', (req, res) => {
  checkCache()
    .then(() => res.json(cache.peek('data')))
    .catch((err) => {
      res.status(500).json({
        error: err.message,
      });
    });
});
```

again, I may just be implementing incorrectly, but I would appreciate any advice or input. :)  It's not entirely clear to me how to use this module for one data set, that I don't want to "refresh" when it's accessed -- rather I want it to be reliably re-cached each hour.

**Comment by isaacs** [comment]
That is correct.  `dispose` is called _before_ the item is fully removed from the cache, so if you want to put the same item (or anything, really) back in, you have to do it on the next tick.  At best, it'll break the recency list in weird ways.

**Comment by isaacs** [comment]
Honestly, I wouldn't use a module for this.  Just do it manually.

```js
let cachedApiResponse = null
let lastUpdatedCachedResponse = 0
const cachedResponseTTL = 1000 * 60 * 60 // 1hr
let cachedApiResponseUpdating = false

const getApiResponse = async () => {
  if (!cachedApiResponse) {
    await updateApiResponseCache()
  }
  if (Date.now() - cachedResponseTTL > lastUpdatedCachedResponse) {
    updateApiResponseCache()
  }
  return cachedApiResponse
}

const updateApiResponseCache = async () => {
  if (cachedApiResponseUpdating) {
    return
  }
  cachedApiResponseUpdating = true
  cachedApiResponse = await fetch('https://api.example.com/')
  cachedApiResponseUpdating = false
  lastUpdatedCachedResponse = Date.now()
}

// then later on, in code....

server.get('/response-maybe-cached', async (req, res) => {
  res.end(JSON.stringify(await getApiResponse())
})
```

**Comment by tconroy** [comment]
Hi @isaacs, appreciate the response :-) And thank you for the snippet! I no longer work on this particular project, but I agree that doing this manually feels like the better approach.

Thank you!

**Comment by isaacs** [comment]
@tconroy i should try to respond to issues with less than a 5 year turnaround, I guess 😅
