### ISSUE TITLE
Set without affecting item age

### ISSUE THREAD

**Issue by andreyrd** [isaacs/node-lru-cache#104]
Sometimes I want to update an item without updating the age of the item.

Maybe this could be done with a flag on `set(key, value, maxAge, updateNow)`. And then `set` could be updated here: https://github.com/isaacs/node-lru-cache/blob/master/lib/lru-cache.js#L321

From:
```
item.now = now
```
To:
```
updateNow = updateNow || updateNow == null // Default to true
...
if (updateNow) { item.now = now }
```

**Comment by isaacs** [comment]
Patch welcome to add an `updateTTL: false` option to `cache.set()` (in v7)
