### ISSUE TITLE
Documentation of Big-O performance?

### ISSUE THREAD

**Issue by mmkal** [isaacs/node-lru-cache#105]
Hi,

What's the best way to find out the big-O performance of the operations? Similar to how redis puts the time complexity at the top of each command: https://redis.io/commands/get (`Time complexity: O(1)`).

Are these documented anywhere? Can they be?

**Comment by isaacs** [comment]
I'd love a patch to add documentation!  Set and get are O(1).  The other things (forEach, etc.) are typically O(n).  But this should be investigated by whoever wants to write the doc patch.

**Comment by joeyhub** [comment]
Set can be O(n) due to trim. However this wouldn't be a normally expected scenario. It would happen if for example you add a spurious entry that has almost MAX length. It would then evict virtually the entire list doing run through.
