### ISSUE TITLE
Provide an abstraction to use it with a custom storage engine, browser localStorage

### ISSUE THREAD

**Issue by gajus** [isaacs/node-lru-cache#106]
or... is the intention that this package is to be used only with node.js?

**Comment by gajus** [comment]
@isaacs any interest in this? or should I look into developing an alternative, browser specific, abstraction?

**Comment by isaacs** [comment]
This is an in-memory O(1) LRU/MRU cache implementation. It just stores JavaScript values in memory.

If you want to customize where things live, you may be interested in the async-cache module, which extends lru-cache with asynchronous (callback-taking) get/set/delete methods.  Then, if your data actually lives on the filesystem, or in localStorage, or a database or wherever you like, you can extend it as needed.  https://www.npmjs.com/package/async-cache

**Comment by isaacs** [comment]
That is, nothing in this module is node-specific, because it's entirely environment-agnostic.  (Apart from using node-like modules with require() and such.)
