### ISSUE TITLE
Add an environment configuration to disable cache

### ISSUE THREAD

**Issue by gajus** [isaacs/node-lru-cache#107]
The logic is similar to the reason https://github.com/gajus/bluefeather#map adds `BLUEFEATHER_MAX_CONCURRENCY` configuration:

> This method is identical to Bluebird#map except that the concurrency setting can be overridden using BLUEFEATHER_MAX_CONCURRENCY environment variable. Controlling max concurrency using environment variables enables debugging of the codebase without refactoring the code.

Sometimes you want to quickly check if cache is the causing the underlying issue. Having a way to disable LRU cache with environment variable would be useful.

**Comment by isaacs** [comment]
I'm not sure what "disable the cache" would mean for this module in a general sense, though, and reaching out to process.env seems like going out of its proper scope.

I'd recommend doing something like this:

```js
const cache = process.env.USE_CACHE === 'none' ? { get: () => undefined, set: () => {}, has: () => false } // cache nothing
  : process.env.USE_CACHE === 'infinite' ? new Map() // cache everything
  : new LRUCache({ ... settings ... }) // do whatever you do
```

Then you can have more control over how this works.
