### ISSUE TITLE
add an "clear()" method (an alias of "reset()") to make the API compatible with Map

### ISSUE THREAD

**Issue by gajus** [isaacs/node-lru-cache#109]
The current API is inconsistent with the [`Map.prototype.clear()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/clear). This results in an error when using `lru-cache` in places where `Map`-like object is expected, e.g. in the case of using `lru-cache` with [DataLoader](https://github.com/facebook/dataloader).

**Comment by gajus** [comment]
The same applies to `del` and [`delete`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/delete). I guess the issue should read: Add aliases to make the API compatible with Map.

@isaacs will you accept a PR for this change?

**Comment by gajus** [comment]
Any chance of this getting attention? It does not need to be a breaking change. This methods can be created as aliases.

**Comment by isaacs** [comment]
Yes these aliases would be fine. PR welcome!

**Comment by prashanthr** [comment]
I see that this issue is still open, so I went ahead and created a PR for this.
https://github.com/isaacs/node-lru-cache/pull/118

**Comment by isaacs** [comment]
v7
