### ISSUE TITLE
cache.get does not work after setting maxAge

### ISSUE THREAD

**Issue by san85** [isaacs/node-lru-cache#110]
Hi,
I am trying to set maxAge for cache entries. But it actually block script execution.

cache.set("id0001", "value", 3000); after 3 seconds cache.get("id0001"); blocks complete execution

Regards
Muthu sankar.M

**Comment by indutny** [comment]
Can't reproduce. Appears to be working just fine. Do you have a minimal test case that exposes the problem?

**Comment by cuiyongjian** [comment]
+1.

my version: 5.1.1
my instance: 

```js
exports.microCache = new LRU({
  max: 10000, // 一个网页html假设100KB，则200MB, 可以存储200000/100=2000个网页
  length (n) { return n.length }
})
```

when i use the length field,  the `lru.set` cannot work. When i remove length field, it is ok.
