### ISSUE TITLE
non-string keys are not fully supported

### ISSUE THREAD

**Issue by remster** [isaacs/node-lru-cache#113]
as claimed [here](https://www.npmjs.com/package/lru-cache)
i.e.: this test does not pass:

```
test('lru accepts non-strings keys', function (t) {
  var cache = new LRU(2)
  cache.set([1, 2], 'A')
  t.equal(cache.get([1, 2]), 'A')
  t.end()
})

```
You should make them fully supported or assert that they're supported as far as javascript object equality permits.

**Comment by siboulet** [comment]
Also running into this issue. Array keys doesn't seems to work.

**Comment by isaacs** [comment]
Those are two different objects, so they're not the same key.  I'm happy to accept a doc patch to clarify this, but if you want to serialize your object keys, you'll have to do that yourself.  JSON.stringify is a good fast choice for simple non-circular objects, and something like http://npm.im/sigmund produces shorter mostly-human-readable keys and (iirc?) it's safe for circular objects.  As @siboulet says, object-hash is also a good choice if you don't care about the keys being human-intelligible.

This functions the same way as a Map object in JavaScript.  (In fact, it's implemented using a Map!)
