### ISSUE TITLE
get() does not update the  "recently used"-ness of the key

### ISSUE THREAD

**Issue by partharamanujam** [isaacs/node-lru-cache#122]
Calling get() for an existing key in cache does not seem to extend the time-to-live in cache.

Consider the following snippet of code:
```
'use strict';

var LRU = require("lru-cache"),
    options = {
        dispose: function (key, n) {
            console.log(key, "Disposed!!!");
        },
        maxAge: 1000 * 15
    },
    cache = LRU(options);

console.log("Setting cache at: " + new Date());
cache.set("key", "value");

setInterval(function () {
    console.log('===> dump', cache.dump());
    console.log(new Date() + " : key => " + cache.get("key"));
}, 1000 * 5);
```

Output is:
> Setting cache at:  2018-02-15T10:14:04.900Z
> ===> dump [ { k: 'key', v: 'value', e: 1518689659900 } ]
> Thu Feb 15 2018 15:44:09 GMT+0530 (India Standard Time) : key => value
> ===> dump [ { k: 'key', v: 'value', e: 1518689659900 } ]
> Thu Feb 15 2018 15:44:14 GMT+0530 (India Standard Time) : key => value
> ===> dump []
> key Disposed!!!
> Thu Feb 15 2018 15:44:19 GMT+0530 (India Standard Time) : key => undefined
> ===> dump []
> Thu Feb 15 2018 15:44:24 GMT+0530 (India Standard Time) : key => undefined

As you can see, the dump shows that the expiry does not change, and the key is disposed-off even after calling get().

**Comment by isaacs** [comment]
Getting a value updates its place in the "most recently used" queue.  It does not update the age of the item.  The point of setting a max age is so that items do not stay in cache for longer than a specific amount of time, even if they are fetched in that time.  This is working as designed.

**Comment by isaacs** [comment]
If you want _access_ to keep a key in the cache, then don't set a maxAge.

**Comment by partharamanujam** [comment]
Okay... makes sense.

I needed something that is dropped if not used (free-up memory) for a long-time, but get extended if used frequently (don't re-create). I solved this by using a combination of `"noDisposeOnSet": true` and calling `set()` after a successful `get()` - I hope this helps anybody else who is looking for a similar solution using this module.
