### ISSUE TITLE
"non-string keys ARE fully supported" ==> not working

### ISSUE THREAD

**Issue by btoueg** [isaacs/node-lru-cache#123]
node 8.9.4
lru-cache 4.1.1

I have to stringify the cache key otherwise it won't work

**Comment by isaacs** [comment]
Please provide a reproducible test case.  Non-string keys work just fine.

```
> LRU = require('./')
[Function: LRUCache]
> l = new LRU()
LRUCache {}
> obj = {}
{}
> l.set(obj, true)
true
> l.get(obj)
true
> obj2 = {}
{}
> l.set(obj2, 1000)
true
> l.get(obj2)
1000
> l.get(obj)
true
```

**Comment by btoueg** [comment]
I won't have the time to provide a minimal reproducible test

**Comment by isaacs** [comment]
@btoueg Ok, well, can you at least describe what you're doing?  As shown above, it does support non-string keys, so I'm confused about what isn't working properly.

**Comment by btoueg** [comment]
Ok, I lied, I can repro easily.

It's happening within Meteor 1.6.1 server-side method, maybe it's messing with Fiber?

To repro:
 1. meteor create my-test-app
 2. change `server/main.js` to:

```javascript
import { Meteor } from 'meteor/meteor';
import LRU from 'lru-cache';

const cache = new LRU(10);

Meteor.startup(() => {
  // code to run on server at startup
});

Meteor.methods({
  twoArgsMethods: function(a, b) {
    cache.set({a, b}, a+b);
    return [cache.keys(), cache.values()];
  }
})
```

 3. in chrome inspector, call the method twice:

```javascript
Meteor.call('twoArgsMethods', 1, 2, (err, data) => console.log(data))
Meteor.call('twoArgsMethods', 1, 2, (err, data) => console.log(data))
```

![image](https://user-images.githubusercontent.com/498190/37121814-99ffc8e2-225e-11e8-80aa-ff37ebc0d0bf.png)

**Comment by isaacs** [comment]
Ok, I see the problem.

```js
    cache.set({a, b}, a+b);
```

When you use an object as a key, the object identity is what matters.  Note that `{a:1} !== {a:1}`.  You'll only get the same value out if you use _the same object_, and in your case, you're creating a _new_ object every time.  So, you used 2 different objects, and got 2 different cache entries, which is working as designed.


```
> l.set({a:1}, true)
true
> l.get({a:1})
undefined
```

**Comment by btoueg** [comment]
Ok, it's unclear in the docs that it works by reference, not by JSON equality.

Docs would be clearer with an example like:

```
var obj = new Object()
l.set(obj, true)
```

Saying out loudly that `"non-string keys ARE fully supported"` makes it confusing

**Comment by btoueg** [comment]
Thanks for the library and reactivity. Sorry for the tone, I'm in a rush!

**Comment by isaacs** [comment]
No worries, I understand.  I'll add a clarification to the doc.
