### ISSUE TITLE
seems to have an issue in the last delivery

### ISSUE THREAD

**Issue by fredericE** [isaacs/node-lru-cache#124]
Hello 
when I use yarn to install the last version, I can see that the version 4.1.2 is downloaded successfully 
(https://registry.yarnpkg.com/lru-cache/-/lru-cache-4.1.2.tgz) 
but it seems that this archive contains files without any dates.. So once unzipped, the date is 1970

16325548649342234     12 -rwxrwxr-x   1 xxx  Domain Users    10619 Jan  1  1970 ./node_modules/lru-cache/index.js
39969446693037343      4 -rwxrwxr-x   1  xxx  Domain Users      765 Jan  1  1970 ./node_modules/lru-cache/LICENSE
16888498602763591      4 -rwxrwxr-x   1  xxx  Domain Users      778 Jan  1  1970 ./node_modules/lru-cache/package.json
10133099161707805      8 -rwxrwxr-x   1  xxx  Domain Users     5447 Jan  1  1970 ./node_modules/lru-cache/README.md

It was not the case for the previous version.  

Thanks in advance

**Comment by deeknow** [comment]
Hey team. Same issue for us. We are loading lru-cache as a dependency of node-mysql2 which we're using in some AWS Lambda functions. The date stamp thing is causing CodeDeploy at AWS to choke when processing a ZIP file containing these as artifacts. Looking forward to a fix.

**Comment by deeknow** [comment]
Hey all. Any further thoughts on this? Would be great to get even just a bump release to fix the datestamp thing?

**Comment by isaacs** [comment]
This is normal npm behavior.  It hard codes the dates in published artifacts, so that they're the same no matter when you publish them, as long as they're the same bits.
