### ISSUE TITLE
Easy bundle size reduction opportunity?

### ISSUE THREAD

**Issue by oliviertassinari** [isaacs/node-lru-cache#125]
I was planning on using the module on the browser. I wanted to check the bundle size implication first. I have noticed that the bundle size sensibly increased between two versions. So, I'm assuming something simple can be done to go back the previous state:
[![capture d ecran 2018-04-19 a 15 47 06](https://user-images.githubusercontent.com/3165635/38995330-f10ee658-43e8-11e8-96a7-ecf0ed8267e5.png)](https://bundlephobia.com/result?p=lru-cache@3.1.2)

**Comment by trivikr** [comment]
Visiting this issue three years later, `node-lru-cache@6.0.0` is 2.6 kB Gzipped
[<img src="https://user-images.githubusercontent.com/16024985/116616063-09353a00-a8f1-11eb-8231-f45a6dd7a39c.png" />](https://bundlephobia.com/result?p=lru-cache@6.0.0)

**Comment by isaacs** [comment]
Probably it's a bit smaller in v7.  But that isn't really a priority, sorry.
