### ISSUE TITLE
Mark cache items to never fall out

### ISSUE THREAD

**Issue by daumann** [isaacs/node-lru-cache#127]
Is there a way to mark a cache item to not compete with others over falling out due to not being used as frequently?

I have one initialization item which every user will query when visiting an application. This item should always be kept in cache. All other items are fine to compete with each other. 

Is that possible?

**Comment by isaacs** [comment]
If you want an item to never fall out of memory, why not just put it somewhere else?

**Comment by daumann** [comment]
For simplicity, I would prefer to only use a single cache library but you are indicating this is not possible with node-lru-cache right now?

**Comment by isaacs** [comment]
Not in any kind of straightforward way, no.  I guess you could bolt a `Map` object onto the side of it, and add a `addPermanent` method or something and override the `get` method to pull it out of there if possible, but I think it's probably simpler to just stash a reference to it somewhere else, and let the lru cache be a true lru.  That's what it says on the tin, after all.
