### ISSUE TITLE
Does the reset() method clear the cache immediately or does it consume some time?

### ISSUE THREAD

**Issue by Shriram-Balaji** [isaacs/node-lru-cache#130]
Hey,

I've been using the lru-cache as follows:

 - Caching the data obtained from an upstream rest call in a GET /data endpoint using `cache.set(cache_key, payload)`
 - Doing a `cached_data.reset()` on the lru-cache when the corresponding DELETE /data REST endpoint is called

I'm not sure if im doing anything wrong, but what seems to be happening is that, when I do a GET /data rest call right after, a DELETE  /data, the expectation is that the cache should be empty. But Im able to get back results from cache.

 So I'd like to know if the `reset` method clears the cache immediately, or if it consumes some time, before which If I try to access the cache, it wouldnt be cleared?

**Comment by lorand93** [comment]
why was this closed? did you find the issue here? I am having the same problem.
Locally when I start the server via ts-node it clears the cache. In the staging environment where the server is started via the built js files the cache clear method is inconsistent....

**Comment by ungarson** [comment]
it should take a couple milliseconds to reset, this is the reset function
```
  reset () {
    if (this[DISPOSE] &&
        this[LRU_LIST] &&
        this[LRU_LIST].length) {
      this[LRU_LIST].forEach(hit => this[DISPOSE](hit.key, hit.value))
    }

    this[CACHE] = new Map() // hash of items by key
    this[LRU_LIST] = new Yallist() // list of items in order of use recency
    this[LENGTH] = 0 // length of items in the list
  }
```
