### ISSUE TITLE
When noDisposeOnSet = true, dispose() is still called on del() calls  

### ISSUE THREAD

**Issue by ea167** [isaacs/node-lru-cache#131]
Hello,

First of all, congrats for this great library, very useful.

When a dispose() function is set and noDisposeOnSet = true, "whenever a set() operation overwrites an existing key" does NOT call dispose().

It seems to me that del() operations should NOT call dispose() either, and noDisposeOnSet=true should only call dispose() when the key expires from the cache.

If not, how can we only capture the keys that expire from the cache?

Thanks!

**Comment by isaacs** [comment]
This is a feature request for a `noDisposeOnDelete` option.  I think I'm gonna just add a reason string to the dispose() calls, that'd be a lot easier.  Then you can just `if (reason === 'evict') ... ` or whatever.
