### ISSUE TITLE
In case of eviction who should win in case of conflict of maxAge and LRU?

### ISSUE THREAD

**Issue by ccinelli** [isaacs/node-lru-cache#138]
This test fails:
```
test('In case we are at max we should evict the values with lower TTL', function (t) {
  var n = process.env.CI ? 1000 : 100
  var cache = new LRU({
    max: 2,
    maxAge: n * 2
  })

  cache.set('a', 'A', n * 10) 
  cache.set('b', 'B', n * 9) 

  setTimeout(function () {
    cache.set('c', 'C')
    t.equal(cache.get('a'), 'A')
    t.notOk(cache.get('b'))
    t.equal(cache.get('c'), 'C')
    t.end()
  }, n)
})
```

It is probably ok. I just think it would be a good idea to clarify the eviction logic

**Comment by isaacs** [comment]
maxAge should always cause an entry to be evicted when visited (optionally treating as a cache miss unless `allowExpired` is set), but we do _not_ preemptively search for outdated entries and expire them.

Do you have an example where it'd be ambiguous?

**Comment by isaacs** [comment]
Ah, yeah, in the test specified, it's working as intended.

`b` is less recently used, so it gets evicted first.  Neither one has timed out yet, so they're both valid.
