### ISSUE TITLE
Latest version breaks due to introduction of generators via yallist package

### ISSUE THREAD

**Issue by jliebrand** [isaacs/node-lru-cache#141]
I could be wrong here, but the latest updates picked up yallist v3 (rather than v2), which introduces the use of generators in it's iterator function. Since I'm using this package in my web app, uglifyjs throws a wobble because it doesn't know about generators. 

Unexpected token operator «*», expected punc «(»

I know I can add the babel runtime for this, but shouldn't the package work for es5 ?

**Comment by melloc** [comment]
I'm hitting this too, thanks to some transitive dependencies that used a `^` dependency for `lru-cache`. Looking at what changed for 4.1.4, it seems like `yallist` didn't need to be updated. Would it be possible to get a 4.1.5 release that reverts back to `yallist@^2.1.2`? (I don't expect 5.x releases to do this; it would just be nice if packages that currently work with older versions of node using the 4.x versions could continue to do so.)

**Comment by ccinelli** [comment]
@isaacs Can you unpublish  `4.1.4` ? It looks like that since it is incompatible with `4.1.3`, it did not follow semver.

**Comment by melloc** [comment]
`npm install` is now pulling in `4.1.5`. Thanks @isaacs!

**Comment by jliebrand** [comment]
Hey guys - I'm still seeing this issue with version 5.1.1 any update on this?

**Comment by isaacs** [comment]
Use version 4 or earlier if you need support for JS engines that don't support generators.
