### ISSUE TITLE
Node version support?

### ISSUE THREAD

**Issue by kanongil** [isaacs/node-lru-cache#146]
I don't see anywhere that specify the supported node versions for the 5.x releases. As such, I'm unable to update to it, since it might not match that of my own module, and a future update might break it.

Can this be clarified?

**Comment by DRoet** [comment]
I could be wrong, but looking at the commits it looks like node 4 was dropped so only node >= 6 is supported

**Comment by kanongil** [comment]
So 5.x is targeting node >= 6.0.0 for compatibility? Where do you get this information?

**Comment by DRoet** [comment]
I do believe so yes, just looking at https://github.com/isaacs/node-lru-cache/commit/9ce69193c4cefbeee27e759b1cf94e02a3eadf8b (commit before 5.0.0 release)
and https://github.com/isaacs/node-lru-cache/blob/master/.travis.yml
(CI only running against node 6, 8 and 10)

**Comment by patrick-mcdougle** [comment]
#144 would solve this problem

**Comment by kanongil** [comment]
This has been fixed for v6.
