### ISSUE TITLE
TypeError: n.close is not a function

### ISSUE THREAD

**Issue by dextherry** [isaacs/node-lru-cache#150]
Hi copied the default example

```
var LRU = require("lru-cache")
  , options = { max: 500
              , length: function (n, key) { return n * 2 + key.length }
              , dispose: function (key, n) { n.close() }
              , maxAge: 1000 * 60 * 60 }
  , cache = new LRU(options)
  , otherCache = new LRU(50) // sets just the max size
```

however, sometimes refreshing the page, it falls and I see a message 
```TypeError: n.close is not a function```

how to fix it?
Thanks

**Comment by pikumar** [comment]
I think we need a better example. For fixing this: 
Please replace dispose: function (key, n) { n.close() } with dispose: function (key, n) { n=""; }

**Comment by alexanderfer** [comment]
Same error here

`var LRU = require('lru-cache')
	, options = { max: 500
		, length: function (n, key) { return n * 2 + key.length; }
		, dispose: function (key, n) { n.close(); }
		, maxAge: 1000 * 60  }
	, cache = new LRU(options);`

and Error:

`TypeError: n.close is not a function
    at LRUCache.dispose (/Project/development/XPTO/myProject/project/server/caching/cacheControll.js:10:6)
    at LRUCache.set (/Project/development/XPTO/myProject/project/node_modules/lru-cache/index.js:175:24)
    at Object.setCache (/Project/development/XPTO/myProject/project/server/caching/cacheControll.js:22:8)
    at Object.exports.getService (/Project/development/XPTO/myProject/project/server/api/user/user.controller.js:128:7)
    at <anonymous>`

**Comment by ephemer** [comment]
Guys, it's an example of disposing of a complex item that needs a specific pattern of cleanup. If you're just storing basic node types like strings etc. just try removing the `dispose: <anything>` option entirely

**Comment by e-tang** [comment]
So in that case, we probably should just comment the "n.close()" with something more meaningful. For anyone who is interested in using it might just grab the example code and test it out.

**Comment by isaacs** [comment]
Doc patch welcome.
