### ISSUE TITLE
maxAge should not be based on the system clock (Date.now() )

### ISSUE THREAD

**Issue by tkarls** [isaacs/node-lru-cache#157]
The problem is when the system clock changes in the background. For instance a server booting with the incorrect time and then NTP sets the clock correctly after a while.

This makes the cache items either live for a very long time (in case the clock was moved backwards) or expire immediately if the clock is moved forward.

**Comment by xamgore** [comment]
@tkarls what would you prefer instead?

**Comment by tkarls** [comment]
@xamgore 
Well, a quick googling suggest the performance API (https://nodejs.org/api/perf_hooks.html#perf_hooks_performance_now) but that became available in v8.5.0

If earlier versions need to be considered then hr_time can be used  (https://nodejs.org/api/process.html#process_process_hrtime_time)

**Comment by isaacs** [comment]
Using `performance.now()` would be good for the next semver major bump.  Will also require adding an `"engines"` declaration to package.json, but even node 8.5 is deep in the graveyard by now.

**Comment by isaacs** [comment]
Uses performance.now() in v7 by default.
