### ISSUE TITLE
version 5.x not es5 compatible

### ISSUE THREAD

**Issue by ayal** [isaacs/node-lru-cache#167]
Is this package written only for node? some packages already use it in client side code:

https://github.com/kuitos/axios-extensions/issues/74

So maybe it makes sense to keep es5 compatibility when releasing?

**Comment by celesteking** [comment]
I'd suggest using babeljs or similar.

**Comment by trivikr** [comment]
The ES5 compatibility was dropped when classes were used in commit https://github.com/isaacs/node-lru-cache/commit/9ce69193c4cefbeee27e759b1cf94e02a3eadf8b, which was released with `v5.0.0`

**Comment by isaacs** [comment]
This is written for node.  If someone wants to use the code in browsers, deno, refrigerators, that's lovely, but it's on them to make it work.
