### ISSUE TITLE
No matching version found for lru-cache@^6.0.0.

### ISSUE THREAD

**Issue by Prabukmca** [isaacs/node-lru-cache#170]
When I try to do npm install, I'm receiving this error.

npm ERR! code ETARGET
npm ERR! notarget No matching version found for lru-cache@^6.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cacache'
npm ERR! notarget

In my package.json, we don't have this lru-cache package. and If I try to install npm i lru-cache@latest, it is always installed with version 5.1.1, 

My global version of this package is always 5.1.1.

When I tried to upgrade angular from 8.1.3 to 10, I have faced the below issue, and when I try to revert my changes still same issue.

[https://stackoverflow.com/questions/63015029/angular-upgrade-from-8-1-3-to-10-facing-issue-as-no-matching-version-found-for-l](url)

**Comment by Prabukmca** [comment]
When I tried to install this paackage with latest, it is always installing with version 5.1.1, How can i fix this issue?

**Comment by leandroandrade** [comment]
Hi. Can you try again? I did it and it worked for me.

**Comment by isaacs** [comment]
Works for me, too.
