### ISSUE TITLE
How to store cached data in redis, instead memory?

### ISSUE THREAD

**Issue by wenlittleoil** [isaacs/node-lru-cache#174]
I think it's a common case that storing the relative cached data in redis or other database, mongo etc, but not in the memory. I have seen this issue #29 . Feel a little confused, want to confirm that is there a more proper way to do that.

**Comment by JsonMa** [comment]
In this condition, you should use redis directly.

**Comment by isaacs** [comment]
https://redis.io/topics/lru-cache
http://npm.im/ioredis
