### ISSUE TITLE
Corrupt JSON with many objects

### ISSUE THREAD

**Issue by Zyles** [isaacs/node-lru-cache#178]
I tried using the cache with 14000 entries totalling a file of 29mb but it seems to become corrupt. Because my script can't read from the cache after it is dumped to disk.

But I limited it to 5000:

```
const cacheMaxAmount = 5000
const cacheMaxAge = 604800000 // 7 days

cache = new LRU({ max: cacheMaxAmount
      , length: function (n, key) { return n * 2 + key.length }
      , dispose: function (key, n) { n.close() }
      , maxAge: cacheMaxAge })




import fs from 'fs'

const initCache = (cacheFileName) => new Promise((resolve, reject) => {
  const data = JSON.stringify({})
  fs.writeFileSync(cacheFileName, data, null, (err) => {
    if (err) {
      reject(err)
    } else {
      resolve()
    }
  })
})

const readCache = (cacheFileName, lruCache) => new Promise((resolve, reject) => {

  if (!fs.existsSync(cacheFileName)) {
    console.log('cacheHelper: Cache file does not exist, creating it at ' + cacheFileName)

    initCache(cacheFileName)
  }

  fs.readFile(cacheFileName, 'utf8', (err, data) => {
    
    if (err) {
      return reject(err)
    }

    try {
      const parsedCache = JSON.parse(data)
      lruCache.load(parsedCache)
      return resolve()
    } catch (ex) {
      return reject(ex)
    }
  })
})

const writeCache = (cacheFileName, lruCache) => new Promise((resolve, reject) => {
  const data = JSON.stringify(lruCache.dump())
  fs.writeFile(cacheFileName, data, null, (err) => {
    if (err) {
      reject(err)
    } else {
      resolve()
    }
  })
})

export {
  initCache,
  readCache,
  writeCache
}
```

Inspecting the file it just says "..." at the end which is not valid JSON of course.

On my second try to read the entire cache into memory I get error:
`SyntaxError: Unexpected token o in JSON at position 30680802`

So I assume there is an upper limit for this usage. Any idea what it is?

Using nodejs.

Would be nice if there were adapters to use SQLite for example. Maybe that can solve the big file sizes.

**Comment by isaacs** [comment]
I don't see any obvious errors in there, but there's no reason why `JSON.stringify()` would produce invalid json.

My best guess is that your node process is closing while trying to write the cache before it's completely flushed to disk, resulting in invalid JSON being written, or you've got multiple instances trying to write at the same time.

I'd recommend checking out https://npm.im/write-file-atomic to avoid those issues.

When you dump it with the node inspector, it's only going to show you a portion of the object by default, so as to not flood your terminal uselessly.  That's not the actual JSON, though.
