### ISSUE TITLE
Setting cache with maxAge 0 causes the cache to never expire

### ISSUE THREAD

**Issue by edwin-tandiono** [isaacs/node-lru-cache#185]
From reading the documentation, I assumed that calling `set` with maxAge argument `0` will cause the cache to immediately expire the same way as calling it with maxAge argument `-1`. However, it seems that the cache ended up never expiring. Is this behaviour intended?

I have created a sample code on https://replit.com/@EdwinTandiono/test-lru#index.js to reproduce this behaviour on version 6.0.0.

**Comment by octo-kumo** [comment]
pretty sure it is, otherwise how would you set infinite expiration

**Comment by jeyendranbalakrishnan** [comment]
Yes, the actual behavior is that maxAge = 0 means infinite expiration.
```
const isStale = (self, hit) => {
  if (!hit || (!hit.maxAge && !self[MAX_AGE]))
    return false
...
```
If hit is defined, then if both hit.maxAge and this[maxAge] are 0, the above always returns false, meaning hit is never declared stale.

Not sure whether this is what is intended though...

**Comment by isaacs** [comment]
It's not infinite expansion if you set a max size, though.  Setting `maxAge:0` just means it doesn't do _time_ based expiration.

Example:

```js
const lru = new LRU({ max: 5, maxAge: 0 })
console.log('initial length:', lru.length)
lru.set(1, 1)
lru.set(2, 1)
lru.set(3, 1)
lru.set(4, 1)
lru.set(5, 1)
console.log('length after 5 sets:', lru.length)
for (let i = lru.length; i < 1000; i++) {
  lru.set(i, i)
}
console.log('length after 1000 sets:', lru.length)
console.log('final cached items', lru.dump())
/*
initial length: 0
length after 5 sets: 5
length after 1000 sets: 5
final cached items [
  { k: 999, v: 999, e: 0 },
  { k: 998, v: 998, e: 0 },
  { k: 997, v: 997, e: 0 },
  { k: 996, v: 996, e: 0 },
  { k: 995, v: 995, e: 0 }
]
*/
```

**Comment by isaacs** [comment]
"LRU" stands for "Least Recently Used".  That is, expire items beyond the max length of the cache which were the least recently used.
