### ISSUE TITLE
max option must be an integer even if maxAge/ttl is set

### ISSUE THREAD

**Issue by mykola-mokhnach** [isaacs/node-lru-cache#193]
Hello,

After upgrading the package to v7 the code started to throw an exception on LRUCache instance creation, because we only provide maxAge value to it, like:

```js
const APPLICATIONS_CACHE = new LRU({
  maxAge: CACHED_APPS_MAX_AGE, // expire after 24 hours
  updateAgeOnGet: true,
  dispose: (app, {fullPath}) => {
    logger.info(`The application '${app}' cached at '${fullPath}' has ` +
      `expired after ${CACHED_APPS_MAX_AGE}ms`);
    setTimeout(async () => {
      if (fullPath) {
        await fs.rimraf(fullPath);
      }
    });
  },
  noDisposeOnSet: true,
});
```

The error stack trace looks like
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=19800&view=logs&j=f164dbd1-368a-58ba-3795-906e0bb83435&t=8e6a9df9-f0b8-5517-a125-44f068bf3227 

Please confirm if this is the expected behaviour or the `max` option must always be provided now even if we only care about TTL

**Comment by isaacs** [comment]
Yes, max capacity must be set even if a TTE is used. I improved performance by pre-allocating the storage space. It needs to know how much to allocate.

**Comment by mykola-mokhnach** [comment]
Thanks. It would probably make sense to explicitly mention this parameter is mandatory in README, because it was not very clear to me.
