### ISSUE TITLE
Getting error as "npm ERR! notarget No matching version found for lru-cache@^7.3.0"

### ISSUE THREAD

**Issue by samarkumar1** [isaacs/node-lru-cache#194]
11:41:45  + npx npm-check-updates -u
11:41:53  npm ERR! code ETARGET
11:41:53  npm ERR! notarget No matching version found for lru-cache@^7.3.0.
11:41:53  npm ERR! notarget In most cases you or one of your dependencies are requesting
11:41:53  npm ERR! notarget a package version that doesn't exist.
11:41:53  npm ERR! notarget 
11:41:53  npm ERR! notarget It was specified as a dependency of 'make-fetch-happen'
11:41:53  npm ERR! notarget 
11:41:53  
11:41:53  npm ERR! A complete log of this run can be found in:
11:41:53  npm ERR!     /home/svchdsn/.npm/_logs/2022-02-09T18_41_52_345Z-debug.log
11:41:53  Install for [ 'npm-check-updates@latest' ] failed with code 1

**Comment by isaacs** [comment]
Looks like a transient cache issue.  Try again?
