### ISSUE TITLE
Mock date to test lru-cache ttl

### ISSUE THREAD

**Issue by teolag** [isaacs/node-lru-cache#198]
I use mock-date to mock the time in my tests. Before version 7 of lru-cache my ttl tests worked fine, detecting items going stale after some time have passed. But now, mock-date does not effect the lifetime of my cached items. 
Is lru-cache nowadays using some other timing than Date and how can I test the ttl in version 7?

**Comment by isaacs** [comment]
Yes, it is using the `performance` object in Node if available.  You can see how I mock it here: https://github.com/isaacs/node-lru-cache/blob/main/test/ttl.js#L1-L32

**Comment by teolag** [comment]
Ah, I see!  Thank you!
