### ISSUE TITLE
updateRecencyOnHas not implemented?

### ISSUE THREAD

**Issue by greghuc** [isaacs/node-lru-cache#199]
Hi there

The current node-lru-cache v7.4.0 mentions an option: "updateRecencyOnHas". Is this actually implemented? A search shows "updateRecencyOnHas" only present in the readme, and the code doesn't mention it: https://github.com/isaacs/node-lru-cache/search?q=updateRecencyOnHas

I ran into this when upgrading for v6.0.0 to v7.4.0, when tests I have that assume this behaviour broke.

Many thanks for a useful library

Greg

**Comment by isaacs** [comment]
Ah!  That was in an early iteration of v7, but got removed.  If you need it, we can either implement it or if not, we can remove from the docs.  Which would you prefer?

**Comment by greghuc** [comment]
I’d appreciate it being implemented - I’d definitely use the updateRecencyOnHas functionality if it existed.

To explain my use-case, I’m using LruCache to hold “recent errors” caught locally in an app and then logged to the cloud. So LruCache holds say the last 100 seen app errors, with a ttl of 5 minutes. The app does LruCache.has(error) before publishing to the cloud. On false, it publishes and does LruCache.set(error). On true, it doesn’t publish. So “same” errors are deduped if they occur within the ttl time window. updateRecencyOnHas fits nicely into this, as it ensures that a regularly occurring error remains in LruCache, and isn’t knocked out if other types of error are also occurring.

**Comment by greghuc** [comment]
Slightly qualifier. If the "recent errors" use case I described can be implemented with current v7 functionality - without updateRecencyOnHas - then I can understand why updateRecencyOnHas functionality is unnecessary and doesn't need implemented. It's nice to have a smaller library API.

**Comment by greghuc** [comment]
Update: I'd be happy for updateRecencyOnHas functionality _not_ to be implemented, and the docs reference removed. I successfully updated to lru-cache latest by using get() instead of has(), as get() also updates cache entry recency.

@isaacs please resolve/close this issue as you see fit, and thanks :-)

**Comment by isaacs** [comment]
:+1: Thanks for the update.  Yeah, if you know that `undefined` isn't a valid value, then `if (cache.get(key) !== undefined)` is a perfectly fine way to check if it's there and also update recency if so.
