### ISSUE TITLE
Default sizeCalculation or specific error message

### ISSUE THREAD

**Issue by bronius** [isaacs/node-lru-cache#221]
It would be nice to have a more specific error message around `sizeCalculation` so that first-time users have an easier adoption.

For string values, the documentation-recommended calculation may be fine:
```
this.cache = new LRU({
  allowStale: true,
  maxSize: 50000,
  sizeCalculation: (n: string) => n.length
});
```
but without it, there is no error. And yet, later on, invoking `this.cache.set(key, val);` with perfectly fine `key` and `val` strings throws the misleading error:
```
TypeError: size must be positive integer
    at LRUCache.requireSize (/.../node_modules/lru-cache/index.js:280:15)
    at LRUCache.set (/.../node_modules/lru-cache/index.js:456:17)
    at SimpleCacheService.set (/.../my-script.ts:15:23)
    ...
```
where a clearer error might be "sizeCalculation" evaluates to `undefined` (or whatever it is)" or "sizeCalculation is not declared" or whatever is most appropriate.

In my limited experience with this module, I found myself spinning in circles until walking with debugger (two separate times separated by just 12 hours! -- bad memory I guess ;)) My example at the top here shows the module works flawlessly. Thank you!

**Comment by isaacs** [comment]
Hmm, yeah, I can see how that might be confusing.

**Comment by bronius** [comment]
😎 
Super! Thanks for the very quick turnaround -- I hope it will be very useful to someone else, too!

A thought on your methodology, however: It _feels_ that `sizeCalculation` is actually required or at least required if `maxSize` is set. These kinds of checks would be great to have in the init (rather than only to be discovered "at run time" in `.set()` validation). Also, in this case, the `typeof` check [will already have been done](https://github.com/isaacs/node-lru-cache/blob/5b34ee3d9bdee76f3e2d3772d61945716289d7e8/index.js#L125) at instantiation, right?
```
    if (this.sizeCalculation) {
      if (!this.maxSize) {
        throw new TypeError('cannot set sizeCalculation without setting maxSize')
      }
      if (typeof this.sizeCalculation !== 'function') {
        throw new TypeError('sizeCalculating set to non-function')
      }
    }
```
Unless sizeCalculation (ooh, it says "sizeCalculating" (sic) in the thrown error msg above)) is allowed to be passed as an option in `.set()` like other options are (I don't recall and didn't confirm).

Cheers!
-Bronius

**Comment by isaacs** [comment]
> Unless sizeCalculation (ooh, it says "sizeCalculating" (sic) in the thrown error msg above)) is allowed to be passed as an option in .set() like other options are (I don't recall and didn't confirm).

Yeah, it is a `set()` option which defaults to whatever is on the object.

Good catch on the typo, I'll fix that 😬
