### ISSUE TITLE
Documented updateAgeOnHas does not exist in code

### ISSUE THREAD

**Issue by marmotz** [isaacs/node-lru-cache#222]
Is it an error in the documentation or a lack in the code ?

Personally, I would like this feature.

**Comment by isaacs** [comment]
It's an error in the documentation that it was not removed when removed from the code 😅 

I'll add it though, it's not hard.  Was just waiting for someone to actually need it.

**Comment by rlittolff-upgraal** [comment]
Nice, thank you :)

**Comment by marmotz** [comment]
Nice ! Thank you :)

**Comment by isaacs** [comment]
Done on 7.8.0 44c5ec96b87bf1a4999ee68ddb8f119dc62bc6f7 (sorry, forgot to tag this issue in the commit)
