### ISSUE TITLE
Ambiguous documentation on requirement of `max` option 

### ISSUE THREAD

**Issue by trevor-scheer** [isaacs/node-lru-cache#224]
The typings specify required, certain parts of the README say required, and others don't.

i.e top of usage section says `max` is required:
https://github.com/isaacs/node-lru-cache#usage

...but most other references to it in the documentation below suggest it's optional (yet disallowed by typings).

I'm happy to submit a PR to update the docs and/or typings, but looking for clarity on the intent first. Thanks!

**Comment by trevor-scheer** [comment]
Update: I was behind on the typings, no issue with them after updating. I do still think there's an incorrect statement to fix (via #226) and things are a lot more clear to me after seeing the latest typings.

**Comment by isaacs** [comment]
I do not manage the type definitions.  The readme is the only docs I maintain, and the code is the final authority.
