### ISSUE TITLE
Possible to add Abort Event to AbortSignal polyfill?

### ISSUE THREAD

**Issue by uplift** [isaacs/node-lru-cache#230]
I'm using version 7.8.1 on top of an DB with an SDK that supports AbortController/Signal.

When I try to use the fetch/fetchMethod and passing the signal to the SDK it errors with `signal.addEventListener is not a function`.

I'm in an environment that falls back to the the AbortController/Signal polyfill within node-lru-cache.

Would it be possible to add the ability to listen for an 'abort' event in the polyfill as specified in https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal?

**Comment by isaacs** [comment]
Can you try this?

```
npm i isaacs/node-lru-cache#isaacs/better-ac-poly
```

and see if that fixes it?

**Comment by uplift** [comment]
Looks like it works to me. Don't get any errors and everything seems to work from my local code testing.
