### ISSUE TITLE
Misleading documentation of sizeCalculation in README in case of invalid return value

### ISSUE THREAD

**Issue by inhibitor1217** [isaacs/node-lru-cache#231]
In `Usage` section in README, `sizeCalculation` is documented as follows:

```js
  // function to calculate size of items.  useful if storing strings or
  // buffers or other items where memory size depends on the object itself.
  // also note that oversized items do NOT immediately get dropped from
  // the cache, though they will cause faster turnover in the storage.
  sizeCalculation: (value, key) => {
    // return an positive integer which is the size of the item,
    // if a positive integer is not returned, will use 0 as the size.
    return 1
  },
```

I believe the phrase `if a positive integer is not returned, will use 0 as the size.` could be misleading. If a positive integer is not returned from `sizeCalculation`, it throws an error `TypeError: size must be positive integer`, rather than using `0` as the fallback size value without failing. Could we fix this section so that the reader can know `sizeCalculation` could possibly throw errors?

**Comment by isaacs** [comment]
Ah, yes, that's carried over from a previous version.  Will fix shortly.
