### ISSUE TITLE
ReferenceError: AbortSignal is not defined in jest tests

### ISSUE THREAD

**Issue by romanlv** [isaacs/node-lru-cache#239]
getting `ReferenceError: AbortSignal is not defined` in jest tests
```

    > 2 | import LRU from "lru-cache";
        | ^

      at Object.<anonymous> (node_modules/lru-cache/index.js:26:5)
...
```

**Comment by antonzy** [comment]
@romanlv same here, strangly it fails in node v16.15.1 but works on older node version v14.18.0

**Comment by isaacs** [comment]
If I'm reading this issue properly, somehow LRUCache is being loaded in an environment where `typeof AbortController` is `'function'` and also `AbortController` is `undefined`.  Without a minimal reproduction, I'm not sure how that's even possible.  My suspicion is that something is modifying the code of the lru-cache module in some invalid way, but I'm definitely not the one doing that.

**Comment by HCanber** [comment]
@isaacs The problem in this case is that `AbortController` is defined (a function) while `AbortSignal` is undefined. It seems like jest is changing things in a strange way. 

The code in this repo only checks `AbortController`. Would you consider changing the code like this this?

``` diff
--  const AS = hasAbortController
++  const AS = typeof AbortSignal === 'function'
      ? AbortSignal
      : class AbortSignal {
```

https://github.com/isaacs/node-lru-cache/blob/efbb661413c80c73d710f06f62e6199b0ddd8ecb/index.js#L25-L27

This change fixed my errors.

**Comment by isaacs** [comment]
Aha, this comes down to some AbortController polyfills that set AbortSignal as a property of AbortController, instead of as a global.

Looks like Jest (or one of the modules it uses) is making such a thing the global AbortController.

Can you try `npm i isaacs/node-lru-cache#pull/243` and see if that fixes the problem?

**Comment by HCanber** [comment]
It works for me as well. :)

**Comment by jpwilliams** [comment]
Yep - working with that PR. 👍

**Comment by zabdalimov** [comment]
Had the same issue when using jest v26, resolved it by upgrading jest to v27.

**Comment by paneq** [comment]
Had the same issue when using jest 27.3.1, updating to 27.5.1 helped.

**Comment by lukagabadze** [comment]
I was having the same issue on jest 29, turns out I had jest-environment-node installed as well with version 26, so there was a version mismatch, I just removed jest-environment-node package and all the global variables started showing up.

Here is a easy test (env-check.test.ts)
```
test("env check", () => {
  console.log("JEST ENV:", globalThis.constructor.name);
  console.log("Event:", typeof Event);
  console.log("EventTarget:", typeof EventTarget);
  console.log("AbortSignal:", typeof AbortSignal);
});
```

In my case the output was:
```
PASS tests/env.test.ts ●
console.log JEST ENV:Object at Object.<anonymous> (tests/env.test.ts:2:11)
console.log Event: undefined at Object.<anonymous> (tests/env.test.ts:3:11)
console.log EventTarget: undefined at Object.<anonymous> (tests/env.test.ts:4:11)
console.log AbortSignal: undefined at Object.<anonymous> (tests/env.test.ts:5:11)
```

After the fix, the output changed to:
```
    console.log
      JEST ENV: Object

      at Object.<anonymous> (tests/env-check.test.ts:2:11)

    console.log
      Event: function

      at Object.<anonymous> (tests/env-check.test.ts:3:11)

    console.log
      EventTarget: function

      at Object.<anonymous> (tests/env-check.test.ts:4:11)

    console.log
      AbortSignal: function

      at Object.<anonymous> (tests/env-check.test.ts:5:11)
```
