### ISSUE TITLE
Provide esm version

### ISSUE THREAD

**Issue by tobiasdiez** [isaacs/node-lru-cache#253]
With more and more build tools (vite, nuxt, etc) going towards an esm-first build, it would be nice if lru-cache could provide a proper [esm interface](https://nodejs.org/api/esm.html), i.e. transpile and distribute esm version, including correct export declaration in package.json

**Comment by isaacs** [comment]
It's not hard to do this, just have a build step that replaces `module.exports =` with `export default`, and copies `index.d.ts` to `esm.d.ts`.

But it is annoying to get the types and test set up properly, since ts-node doesn't regard `.mjs` as a valid extension to load.  Patch welcome, as long as it's as unobtrusive as possible.

In the meantime, I believe even most esm-first environments _can_ load commonjs modules, so the path of least resistance for users seems to be leaving this as cjs, rather than going full-esm.

**Comment by tobiasdiez** [comment]
>It's not hard to do this, just have a build step that replaces module.exports = with export default

There are also build tools / scripts such as https://github.com/unjs/unbuild that help with this dual setup.

>... and copies index.d.ts to esm.d.ts. But it is annoying to get the types and test set up properly, since ts-node doesn't regard .mjs as a valid extension to load. Patch welcome, as long as it's as unobtrusive as possible.

Not sure if I understand but type definition files should stay untouched and don't need to be distributed in a different format (they stay typescript).

> In the meantime, I believe even most esm-first environments can load commonjs modules, so the path of least resistance for users seems to be leaving this as cjs, rather than going full-esm.

Mostly yes, sometimes you need to help them by letting them know which modules to transpile, which then has to transverse the whole dependency tree. Also there are issues with tree shaking, which would be nice to have for smaller server builds for edge / serverless.

**Comment by isaacs** [comment]
> Not sure if I understand but type definition files should stay untouched and don't need to be distributed in a different format (they stay typescript).

Ah, I thought if I'm shipping a different filename, the .d.ts has to match it.  The hybrid modules I've been building lately seem to need a .d.ts next to both the esm and the cjs files.

**Comment by tobiasdiez** [comment]
Since there is only one entry point, something like the following in `package.json` should do the job:
```
"exports": {
    ".": {
      "import": "./dist/index.mjs",
      "require": "./dist/index.cjs"
    }
  },
  "main": "./dist/index.cjs",
  "types": "./dist/index.d.ts",
```
and then a script that copies the current `index.js` (+ transpile it to esm) and `index.d.ts` to `dist`. Alternatively, you could convert `index.js` to typescript and then use something like https://github.com/unjs/unbuild to build esm + cjs + d.ts from it.

**Comment by eugene1g** [comment]
@isaacs I can do a minimal PR (for JS and TS sides) to implement this - would you review it, or busy right now?

**Comment by isaacs** [comment]
Sure I'd be able to review. The final pattern that seems to work for all combinations of default export, types, commonjs, and esm, without breaking webpack, is in rimraf and mkdirp right now, if you want to look at those as examples. A build script is fine, if it helps.

**Comment by eugene1g** [comment]
Closed by https://github.com/isaacs/node-lru-cache/commit/4f6ba91e524461073aa81291d2fcfa6910ba7aa5 thanks @isaacs 👏
