### ISSUE TITLE
Collision with abort-controller

### ISSUE THREAD

**Issue by omer727** [isaacs/node-lru-cache#255]
This library cause me collision with 'node-fetch' and 'abort-controller'.
How to reproduce:
1. just import 'lru-cache';
2. import 'node-fetch' and 'abort-controller':
3. The following code will throw new TypeError('Expected signal to be an instanceof AbortSignal')
```
const controller: AbortController = new AbortController();
const timeoutId = setTimeout(() => controller.abort(), 10 * 1000); //10 seconds timeout
const fetchParams: RequestInit = {
        headers: {},
        method: 'GET',
        signal: controller.signal,
    };
await fetch('http://github.com/', fetchParams); //do the actual http request
```

It's because 
- LRU Cache set AbortController as global variable
- When importing the AbortSignal constructor from abort-controller library it defines it as AbortSignal2
- The condition on node_modules/node-fetch/lib/index.js:1185 because it's expecting AbortSingal and the constructror we have is AbortSingal2 => 
it is failing and throw new TypeError('Expected signal to be an instanceof AbortSignal')

**Comment by isaacs** [comment]
Oh, the battle of the polyfills, I'm sorry.

You can work around it for now by changing the import order, or pulling in a specific global AC polyfill initially, but yes, this is annoying.  I'm not sure the best way around it, since both libraries are trying to polyfill the same missing global.

**Comment by isaacs** [comment]
When support for v14 and earlier drops, we can remove this polyfill.  Until then, we're stuck with workarounds.  Load `node-fetch` first, or update node to v18 and use its built-in fetch implementation.
