### ISSUE TITLE
lru-cache CACHED.has('test')一直都是返回false

### ISSUE THREAD

**Issue by 1047415098** [isaacs/node-lru-cache#258]
![image](https://user-images.githubusercontent.com/28483622/203689702-4b57e605-db63-4796-bedf-54758cd3d815.png)

lru-cache 7.14.1 版本 
![image](https://user-images.githubusercontent.com/28483622/203689806-9dfb9409-1812-47d9-8d0b-cf1f75df30da.png)

CACHED.has('test')一直都是返回false

**Comment by isaacs** [comment]
You've commented out the line where it's setting a value, so returning `false` is expected behavior.

Please post code in text, not images.
