### ISSUE TITLE
[Question]: Does this follow a singleton type design?

### ISSUE THREAD

**Issue by TannerS** [isaacs/node-lru-cache#261]
So what i mean is, if I create an instance of LRU cache in a file, and that file gets called multiple times for multiple api request, is that instance re-created (basically re-creating the initial cache or will it remember it was created in prior api call and use the data from there?

**Comment by isaacs** [comment]
This class does not enforce a singleton, no, that would be a bad idea, since you might need to cache multiple different sorts of things!

But modules in node _are_ singletons.

So, for example, this is probably what you want to do:

```ts
// in src/routes/api.ts or something
import LRUCache from 'lru-cache'

// only create one fooCache for this _module_, which is a singleton
const fooCache = new LRUCache<string, Foo>({
  max: 10000,
  ttl: 1000 * 60 * 60, // 1hr
  fetchMethod: async (key) => await getNewFoo(key),
})

export const getFoo = async (params) => {
  const foo = await fooCache.fetch(params.foo).catch(er => {
    console.error('foo error', params, er)
    return new Response(JSON.stringify({ message: 'error fetching foo' }, 500))
  })
  return new Response(JSON.stringify(foo))
}
```

Then if you had another file that did something like this:

```ts
// src/routes/other.ts
import { getFoo } from './api'
import { otherThing } from './other-thing'
export const otherEndpoint = async (params) => {
  if (params.foo) {
    return getFoo(params)
  } else {
    return otherThing(params)
  }
}
```

then it'll still always use the module-local `fooCache`.

However, this would almost certainly _not_ be what you want:

```
// in src/routes/api.ts or something
import LRUCache from 'lru-cache'

export const getFoo = async (params) => {
  // oh no!  We're not actually caching anything, because
  // we throw the cache away and create a new one on
  // each API request!  That's no good!
  const fooCache = new LRUCache<string, Foo>({
    max: 10000,
    ttl: 1000 * 60 * 60, // 1hr
    fetchMethod: async (key) => await getNewFoo(key),
  })
  const foo = await fooCache.fetch(params.foo).catch(er => {
    console.error('foo error', params, er)
    return new Response(JSON.stringify({ message: 'error fetching foo' }, 500))
  })
  return new Response(JSON.stringify(foo))
}
```

Hope that helps.

**Comment by isaacs** [comment]
Note that in some platforms' dev environments, the module cache is blown away on every code change, or even on every request, so you won't see any caching happening.  One workaround for that is to put the cache on the `global` object, and only recreate it if it's missing, so that you don't get it blown away on each update.

**Comment by TannerS** [comment]
Thanks for the examples, I'll take a look when I get back to my desk. Basically, in this code based we are working with, it is a server that processes x different API calls. In each API call. It may go through many files that process the info..

What we are seeing is, there's endpoints that run through diff files (modules) that create a new instance of LRU cache using the new keyword, and then using it's setters and getters.

So imagine if you will, someone sends an API request, it reaches out server (running express), and each time an API calls is made, somewhere in that path of function calls it creates a new instance of LRU and uses it

Does that mean it is incorrect? Since after the code runs, the server instance and connection ends? So next API call the cache would be empty cause it just creates a new instance?


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TannerS** [comment]
@isaacs

**Comment by isaacs** [comment]
Sorry I missed this comment. 

Yes, you definitely need to be creating the cache in some long-lived fashion (ie, NOT in a request handler function or transient serverless handler), or else it's not making anything faster, but rather quite the opposite.

It's probably fine to create the cache lazily, so the first request is slower but repeated requests are faster, but the cache does need to live long enough to actually have cache hits, or it's just pure cost with no benefit.
