### ISSUE TITLE
inprove docs/error message when size cant be determined and maxSize is set

### ISSUE THREAD

**Issue by SeiwonPark** [isaacs/node-lru-cache#264]
According to [docs](https://github.com/isaacs/node-lru-cache#setkey-value--size-sizecalculation-ttl-nodisposeonset-start-), using `sizeCalculation()` is **Optional**.

---
### set(key, value, [{ size, sizeCalculation, ttl, noDisposeOnSet, start }])
Add a value to the cache.

**Optional options object may contain ttl and sizeCalculation as described above**, which default to the settings on the cache object.

---

But to use `set()` function it doesn't seem to work without `sizeCalculation()` option.

Here's an example

```javascript
// index.js
const LRU = require("lru-cache");

const cache = new LRU({
  maxSize: 1,
});
cache.set(1, 1000);
console.log(cache.get(1));
```

Error message:

```
TypeError: invalid size value (must be positive integer)
```

But with `sizeCalculation()` option,

```javascript
// index.js

const LRU = require("lru-cache");

const cache = new LRU({
  maxSize: 1, // required to use sizeCalculation()
  sizeCalculation: (value, key) => {
    return 1;
  },
});
cache.set(1, 1000);
console.log(cache.get(1));
```

So I guess the documentation needs to be updated. `Optional` -> `Required` and the type as well `sizeCalculation?` -> `sizeCalculation`

Or do I miss something here?

**Comment by minho-comcom-ai** [comment]
Thank you for reporting this issue! I found the bug on our production.

**Comment by minho-comcom-ai** [comment]
Oh! I found following statement on README:
```
When maxSize is set, every item must provide a size, either via the sizeCalculation method provided to the constructor, or via a size or sizeCalculation option provided to cache.set().
```

**Comment by isaacs** [comment]
Yeah... sorry that is a little convoluted. I suppose the types could be updated, but it'd be kind of a mess. There's have to be variants for the class with and without maxSize, and with and without sizeCalculation, and then the set method with and without both size and sizeCalculation options. 

At least the error and docs could be more helpful in calling that out, I guess. Reopening as a docs/error wording issue.

**Comment by isaacs** [comment]
For fun, I took a pass at trying to get the type hinting to indicate all the times when size is allowed or required, by defining restricted types like `type LRUOptionsNoSize<K, V> = LRUOptions<K, V> & { maxSize?: undefined }` and so on, and then inferring the type of the options object, and passing that reference around on the type to choose different options types for `set()`, `fetch()`, etc.  

I think it's not actually possible, at least, not without much more TypeScript complexity than I care to manage here.  Another way to do this would be to have separate subclasses for all the different option types, and then mixing features (like if you have TTL _and_ size, or size and no sizeCalculator on the instance, etc.) quickly becomes a combinatorial explosion that the user has to deal with.  Vs just letting everything be marked "optional" and do the run-time checks, which is just as performant and more flexible to more use cases, with less code.

So yeah.  Just sticking with the plan here.  No type hinting for when `size` is required, just run-time checks that are more useful than they used to be.
