### ISSUE TITLE
[Feature request] Provide fetch status to caller

### ISSUE THREAD

**Issue by yoshigev** [isaacs/node-lru-cache#271]
Hi,

Thanks for the great library.

We have started using this library for different use-cases, and find `fetch` method to suit almost all of them.

One of the few features that we're missing, is a way for the caller of `fetch` to get an indication of whether it was a cache-hit, a cache-miss or returning a stale value (due to `allowStale`).
This is required both for logging and for statistics.

### Workaround
A possible workaround we found is passing a `fetchContext` object and update it inside the `fetchMethod`.
For example:
```javascript
import LRU from 'lru-cache';

const cache = new LRU({
  max: 1000,
  fetchMethod: (key, stale, options) => {
    options.context.fetched = true;
    return 'a';
  }
});

async function test() {
  const fetchContext = { fetched: false };
  console.log(await cache.fetch('x', { fetchContext }), fetchContext);
}

test();
// Output: a {fetched: true}
test();
// Output: a {fetched: false}
```

But this can still give not indication whether the value was stale.

### Proposal

I think that a possible solution is similar to my workaround, but having it done by the library.
For example:
```javascript
  const cacheStatus = {};
  const res = await cache.fetch('x', { cacheStatus })
```
Having cacheStatus be filled with properties like:
```javascript
{
  cacheHit: true,
  isStale: false,
  ttl: 10000,
  remainingTtl: 432
}
```

Thanks!

**Comment by isaacs** [comment]
That's a good idea. An updated `status` object could be useful on set and get as well.
