### ISSUE TITLE
Drop support for Node < 16

### ISSUE THREAD

**Issue by isaacs** [isaacs/node-lru-cache#272]
In next major version, dropping support for node 14 and below would mean we could get rid of the AbortController/AbortSignal polyfill, and potentially also lean on some other features of the interface to do timeouts and other stuff (as suggested in #268).

Might also be time to just bite the bullet and rewrite in TypeScript? Would have to make sure that the CJS transpilation doesn't impact performance, but then also the ESM could be built in the same way as my other libraries, which would be a bit less of a context switch for me when working on this one.

**Comment by eugene1g** [comment]
+1 for moving `lru-cache` to TypeScript, especially if you already write in TS for your other/newer libraries. I can help around the edges, without butting into the core.
