### ISSUE TITLE
Does this work across different files within same instance?

### ISSUE THREAD

**Issue by TannerS** [isaacs/node-lru-cache#276]
Hello! question about this. If i have a web server (express) and i want to cache the results of a commonly used endpoint, would this cache the results for everytime a user connects to the express erver endpoint? or does it work in a diff way? Basically, we want to cache some stuff in our endpoint but since the code at that endpoint runs only when connected too, i would like to verify this is correct use

**Comment by isaacs** [comment]
If you want to make the cached data survive server restarts or work across different processes, that'll take some added work, but the tools are there to do that, if you get clever with the `cache.dump()` and `cache.load()` features, and make sure to use data that survives JSON serialization.  Ie, use a scalar data type like string or number as the key, and scalars or JSON-friendly plain old objects as data.  Then what you can do is dump the cache to a database or file on changes, and read it out on server startup or something.  Nontrivial, but not rocket surgery.

If you're just looking for something that's going to be local to a process or a given module, yeah, that's pretty much what it does out of the box.  It's not necessarily tied to caching "responses" though, it's just a general purpose data cache for whatever you wanna put in it.

```js
// some express route...
const cache = new LRUCache({
  // cache settings go here...
  ttl: 1000 * 60 * 60 * 24, // cache for a day
  max: 1000, // don't cache more than this many things

  // could do it this way, or fetch yourself and use get/set/has yourself
  // the benefit of fetchMethod is that you get inflight coalescing for free
  fetchMethod: async (key) => {
    return getThingFromDatabaseOrWhatever(key)
  },
  // whatever other optional other settings you might want, eg:
  allowStaleOnFetchRejection: true, // if the fetch fails, serve stale data, if we have it
})

app.get('/some/endpoint/:key', async (req, res, next) => {
  // my express memory might be out of date...
  cache.fetch(req.params.key).then(result => res.json(result))

  // or, if you want to do it all manually, this works, too:
  const cached = cache.get(req.params.key)
  if (cached !== undefined) {
    res.json(cached)
    return
  }
  const fresh = await getThingFromDatabaseOrWhatever(req.params.key)
  cache.set(req.params.key, fresh)
  res.json(fresh)
})
```

I fairly often will create a caching "model" file in my app, which uses the fetchMethod, and exposes just an async get function.

```js
// app/models/dog.ts
import LRUCache from 'lru-cache'
const { DOG_API = 'https://api.dogs.com' } = process.env
const cache = new LRUCache({
  max: 10000,
  ttl: 1000 * 60 * 60, // 1 hour
  fetchMethod: async (key, oldValue, { signal }) => {
    const res = await fetch(String(new URL('/v1/dogs/' + key, DOG_API))
    return await res.json()
  },
  allowStaleOnFetchRejection: true,
  allowStaleOnFetchAbort: true,
})

export const getDog = async (key: string) => {
  // never take more than 100ms to return *something*, or give up
  // and use stale data
  return cache.fetch(key, { signal: AbortSignal.timeout(100) })
}
```

then anywhere else in your app, you can do:

```ts
import { getDog } from '../models/dog'

app.use('/v1/dog/:key', async (req, res) => {
  try {
    res.json(await getDog())
  } catch (er) {
    // didn't have anything in cache, AND the fetch failed or timed out
    console.error(er)
    res.status(500)
    res.send(er.message)
  }
})
```

Hope that helps!

**Comment by isaacs** [comment]
Note that either of these approaches will use the *same* cache for all users of your application.  So anything that's specific to a given user will have to be somehow reflected in the cache key that you use.  But you could have a route like `/v1/thing/:key` that uses `key + ':' + userid` as the cache key, etc.

**Comment by TannerS** [comment]
Cool ya I don't mean across processes I just mean one server instance on multiple endpoint hits

Thanks!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by isaacs** [comment]
Yeah, that should be fine, then.  Caches are pretty cheap, I usually find it's best to spin up a dedicated one for each "thing" right at the point where you'd be making whatever slow request/computation it saves, rather than try to have one cache to host multiple different kinds of things, especially if they might need different semantics.

**Comment by TannerS** [comment]
thanks man :)

**Comment by TannerS** [comment]
@isaacs  one last question, if you wanted diff configs for diff resources, like for example, if i did 

```
const cache = new LRU({
  max: 500,
  ttl: 1000 * 60 * 15,
  updateAgeOnGet: false,
  updateAgeOnHas: false,
});
```

that has max of 500 and so on, but if i wanted something else to have a max of ...idk...25..... can i do the above twice in two diff files? and each will be there own cache instance (for a lack of a better word) or will it overwrite it somewhere?

right now i have a local module with setters and geetters that uses lru-cache and i use this local module in multiple places in my server, but im wondering how to change the config for some data (for some cache)

**Comment by isaacs** [comment]
You can definitely instantiate as many caches as you need. Their data is completely separate from one another. They are fairly cheap to keep around, and it makes the logic a whole lot simpler and more flexible if each cache is just one sort of "thing".
