### ISSUE TITLE
rewrite in TypeScript

### ISSUE THREAD

**Issue by isaacs** [isaacs/node-lru-cache#279]
The types for this module have some unfortunate complexity and aren't entirely accurate.  Also, there've been a couple recent bugs around exposing background fetches and undefined key handling that would have been quickly caught by using types.  (In fact, that's how I caught the most recent one, doing this refactor.)

Not going to even attempt to catch all the various cases in which, eg, either `size` or `sizeCalculation` are required, but only one of them is relevant, and only if there's a maxSize or maxEntry size, but not a cache-level sizeCalculation, etc.  Runtime checks and docs for that.  But it's still worth doing, and the transformed JS if we limit to node 16 and higher is really not so bad.

**Comment by isaacs** [comment]
Breaking changes:
- types change somewhat (if only how the options are defined)
- going to drop the AbortController/AbortSignal polyfill at the same time

**Comment by eugene1g** [comment]
You could express more constraints within the new code - 

- TypeScript: mark [public properties](https://github.com/isaacs/node-lru-cache#cachemax-cachemaxsize-cacheallowstale) as `readonly` (e.g., `maxSize`, `allowStale`,...).
- Node: you could use `#private` to fully hide [internal methods and properties](https://github.com/isaacs/node-lru-cache#internal-methods-and-properties) (e.g. `connect`,  `moveToTail`...)

**Comment by isaacs** [comment]
@eugene1g Yeah, I plan to move the internal stuff actual private properties, but there are some tests that poke around in there, so it's a bit of work to refactor those.

Most of the option properties can be changed without any real hazard, it'll just change the new defaults for all subsequent requests.  `max` is an exception, though, I think that'll move to `#max` with a getter, to make it actual read-only.

**Comment by eugene1g** [comment]
> there are some tests that poke around in there, so it's a bit of work to refactor those.

The way I handle this is to have a private implementation, but expose a "public" property using a private `Symbol` that would allow my test to reach the internal state. So, something like this -
```ts
// create src/test-hints.ts
export const privateMoveToTail = Symbol('moveToTail')

// in index.ts
import { privateMoveToTail } from "./test-hints.ts";

class LRU {
  // ...
  #moveToTail(index: Index) {
     // normal implementation
  }

  // At the end of the class, provide proxies to internal methods
  [privateMoveToTail](idx:Index){
    this.#moveToTail(idx)
  }
}

// in test/move-to-tail.ts
import { privateMoveToTail } from "../src/test-hints.ts";
// ...
t.test('list integrity', { bail: true }, t => {
  // ...
  //@ts-expect-error
  exp[privateMoveToTail](2)
  t.matchSnapshot(snap(), 'list after moveToTail 2')
  integrity('after moveToTail 2')
  //@ts-expect-error
  exp[privateMoveToTail](4)
  t.matchSnapshot(snap(), 'list after moveToTail 4')
  // ..
```

Verbose, and hacky, but explicit and only have to do this scaffolding once. May there could be some clever indirection through a `Proxy`, or some callback style method.
