### ISSUE TITLE
CJS is broken on v8 with Typescript

### ISSUE THREAD

**Issue by orgads** [isaacs/node-lru-cache#283]
Hi,

With v8, the import statement changed from:

```typescript
import * as LRU from 'lru-cache';
const cache = new LRU<string, string>({ max: 10 });
```

to:
```typescript
import LRU from 'lru-cache';
const cache = new LRU<string, string>({ max: 10 });
```

But transpiling this for CJS gives:
```js
const lru_cache_1 = require("lru-cache");
const cache = new lru_cache_1.default({ max: 10 });
```

and this fails on runtime with the following error:
```
const cache = new lru_cache_1.default({ max: 10 });
              ^

TypeError: lru_cache_1.default is not a constructor
```

**Comment by isaacs** [comment]
Ah, yes, that was an oversight.  Thanks for reporting :)

**Comment by orgads** [comment]
Thank you for the quick fix! :)

**Comment by holgerd77** [comment]
Hi there,
I wonder if there is still something off along the latest (v8.0.4) release or build process regarding CJS/ESM.

So we just wanted to use v8.0.4 and I imported with:

```typescript
import LRUCache from 'lru-cache'
```

This works fine for Node (in our tests) but for Karma this breaks with:

```shell
28 03 2023 13:25:34.039:ERROR [source-reader.karma-typescript]: Error parsing code: Unexpected token (51:8)
in/ethereumjs-monorepo/packages/statemanager/node_modules/lru-cache/dist/cjs/index.js
at line 51, column 8:

... ;
    length;
    // private constructor
    stati ...
```

Some eventually useful context from the Karma config:

```typescript
module.exports = function (config) {
  config.set({
    frameworks: ['karma-typescript', 'tap'],

    // list of files / patterns to load in the browser
    files: ['./src/**/*.ts', './test/**/*.ts'],

    // list of files / patterns to exclude
    exclude: [],
    preprocessors: {
      '**/*.ts': ['karma-typescript'],
    },
    karmaTypescriptConfig: {
      tsconfig: './tsconfig.json',
      bundlerOptions: {
        entrypoints: /\.spec\.ts$/,
        acornOptions: {
          ecmaVersion: 12,
        },
      },
    },
    browsers: ['FirefoxHeadless', 'ChromeHeadless'],
  })
}
```

I then "solved" the issue (for us this is sufficient for now, so just posting here in case this is helpful) by going down to `7.18.3` and importing on the lines of:

```typescript
import type LRUCache from 'lru-cache'

const LRU = require('lru-cache')
```

(I wanted to preserve the typing)

So this worked for `7.18.3`. Interestingly this broke again (tested this in addition) if going back with this to `v8.0.4` with `lru_cache_1.default is not a constructor`.

Sorry for the broad description with some lack of analysis, I am not so much of an ESM/CJS/Build expert, hope this nevertheless gives enough context for someone to analyze.

**Comment by holgerd77** [comment]
Update: ah sorry, no confirmation on this out-of-memory thing, this is happening on v7 too (so likely a bug on our side)

**Comment by isaacs** [comment]
The `ecmaVersion: 12` config is telling it not to allow class property declarations.  Change that to `ecmaVersion: 14` (or `ecmaVersion: 'latest'`) and the problem should go away.

**Comment by isaacs** [comment]
> Update: ah sorry, no confirmation on this out-of-memory thing, this is happening on v7 too (so likely a bug on our side)

If you can isolate the memory leak issue, or even just share a bit of how you're using the cache, I might be able to provide some help. LRUCache definitely shouldn't leak memory, but any caching is liable to *use* a lot of memory, if not limited properly.

**Comment by holgerd77** [comment]
> > Update: ah sorry, no confirmation on this out-of-memory thing, this is happening on v7 too (so likely a bug on our side)
> 
> If you can isolate the memory leak issue, or even just share a bit of how you're using the cache, I might be able to provide some help. LRUCache definitely shouldn't leak memory, but any caching is liable to _use_ a lot of memory, if not limited properly.

Thanks, but after additional analysis it is not even clear that the cache is the original issue any more and I don't want you to distract into "stuff". 😋

In case I have some solid confirmation on something I'll head back here.

Thanks for the help above! 🙏
