### ISSUE TITLE
fetch(): is it still inflight-unique?

### ISSUE THREAD

**Issue by eugene1g** [isaacs/node-lru-cache#284]
README says:

> If you call fetch() multiple times with the same key value, then every call after the first will return the same promise

Which reads like the `fetch` method will return the same `Promise` instance, but that's not the case right now:
```ts
import LRUCache from "lru-cache";

const c1 = new LRUCache<number, number>({
  max: 5,
  fetchMethod(k) {
    return new Promise((res) => setTimeout(() => res(k), 10));
  },
});

const r1 = c1.fetch(1);
const r2 = c1.fetch(1);
const r3 = c1.fetch(1);
console.log(r2 === r3); // false
```

Am I misunderstanding the definition of `return the same promise`?

**Comment by isaacs** [comment]
Ah, yes, the wording is not precisely accurate there. What it should say is that it's one call to fetchMethod, so the second promise will resolve along with the first one.

**Comment by isaacs** [comment]
Minimal example of what's going on there:

```js
let pp = null
const a = async () => {
  const p = new Promise(res => setTimeout(res))
  pp = p
  return p
}

const froma = a()
console.log(froma === pp) // false
```

Ie, when an `async` method return a promise, the value actually returned by the async method is not "that promise", it's a promise that resolves at the end of the Promise tick when that one does.  For example:

```js
let pp = null
const a = async () => {
  const p = new Promise(res => setTimeout(res))
  pp = p
  return p
}

const main = async () => {
  const froma = a()
  // Promise {<pending>}, Promise {<pending>}, false
  console.log(froma, pp, froma === pp)

  await pp
  // Promise {<pending>}, Promise {undefined}, false
  console.log(froma, pp, froma === pp)
  await Promise.resolve()
  // Promise {undefined}, Promise {undefined}, false
  console.log(froma, pp, froma === pp)
}

main()
```
