### ISSUE TITLE
canched value can only be object

### ISSUE THREAD

**Issue by tjx666** [isaacs/node-lru-cache#290]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/41773861/232537868-46d6379d-f6d1-4902-903c-3f05e289eb39.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/232537978-c2400dfe-b0fd-47e7-9fc2-8a274c664e8c.png">

**Comment by isaacs** [comment]
Yes, it uses `undefined` as a signal in some cases to mean that the item is not found, and this will cause incorrect behavior. Don't put `undefined` in the cache. If you want a key to be undefined, delete it.

I suppose the `set` method could be changed to allow `cache.set(key, undefined)` to be an alias for `cache.delete(key)`, would that be to your liking?

The downside, I guess, would be if you wanted `cache.has(key)` to return true?

**Comment by isaacs** [comment]
Another option would be to use a special object that means "no value here", so it would "have" the object, but still return undefined from cache.get?
