### ISSUE TITLE
In typeScript can use string as key

### ISSUE THREAD

**Issue by victorGS18** [isaacs/node-lru-cache#298]
I have started to use this library in a project and I have seen that it does not compile in typeScript because the LRUCache key has to extend from {}. 
Is this something done on purpose, or is it a bug?

**Comment by isaacs** [comment]
`string` does extend from `{}`, though.  That is the base type for everything other than `null`, `undefined`, and `unknown`.

What version of typescript are you using? What error are you seeing?
