### ISSUE TITLE
Cannot read private member #keyMap from an object whose class did not declare it

### ISSUE THREAD

**Issue by overdev-l** [isaacs/node-lru-cache#304]
this.cache.has("https://image.liuyongzhi.cn/video/Walk_15000ms.mp4")

**Comment by overdev-l** [comment]
Only when there is this key will throw this exception

**Comment by isaacs** [comment]
What is "this.cache"? Please provide a full example of the problem if you can.

**Comment by overdev-l** [comment]
this is my Parse class
`
namespace ParserConfig {
  export interfaca LRUData {
  source: Blob
  url: string
  }
}



class Parser {
    cache = new LRUCache<string, ParserConfig.LRUData>({
        max: 100,
        maxSize: 500,
        sizeCalculation: (value) => {
            return Math.ceil(value.source.size / (1024 * 1024))
        },
        dispose(value) {
            URL.revokeObjectURL(value.url)
        },
    })
}
`
In fact, when the cache is empty, there is no problem using the`has` function, but if there is a key to be verified in the cache, it will tell me that `#keyMap ` is private

**Comment by overdev-l** [comment]
This is my Parse class
```typescript
namespace ParserConfig {
	export interfaca LRUData {
	source: Blob
	url: string
	}
}

class Parser {
	cache = new LRUCache<string, ParserConfig.LRUData>({
		max: 100,
		maxSize: 500,
		sizeCalculation: (value) => {
		return Math.ceil(value.source.size / (1024 * 1024))
		},
		dispose(value) {
		URL.revokeObjectURL(value.url)
		},
	})
}
```

 In fact, when the cache is empty, there is no problem using the `has` function, but if there is a key to be verified in the cache, it will tell me that `#keyMap ` is private

**Comment by overdev-l** [comment]
> What is "this.cache"? Please provide a full example of the problem if you can.什么是“this.cache”？

This is my Parse class
```typescript
namespace ParserConfig {
	export interfaca LRUData {
	source: Blob
	url: string
	}
}

class Parser {
	cache = new LRUCache<string, ParserConfig.LRUData>({
		max: 100,
		maxSize: 500,
		sizeCalculation: (value) => {
		return Math.ceil(value.source.size / (1024 * 1024))
		},
		dispose(value) {
		URL.revokeObjectURL(value.url)
		},
	})
}
```

 In fact, when the cache is empty, there is no problem using the `has` function, but if there is a key to be verified in the cache, it will tell me that `#keyMap ` is private
