### ISSUE TITLE
Engines constraint

### ISSUE THREAD

**Issue by ilnicki** [isaacs/node-lru-cache#306]
Hi, encountered the library as one of my peer dependecies (trough rimraf) and got some throubles with it. Currently I have node v16.13.2 on my CI servers and on production one and yarn installing fails due to engines constraint in this one. So the questions:
Is there any particular reason for engines constraint to be "14 || >=16.14"? Is there anything 16.13 laсks for the package to work? Can it be lowered if none?

I've run it locally with --ignore-engines and everything seems fine.

**Comment by isaacs** [comment]
I believe it relies on the AbortSignal interface change that happened around then, so fetch() is not correct without it in some cases. If you know you aren't using the parts affected, then great! But the fact that it made you pause and apply a workaround is the system working as intended, so no, I'm not going to change it.
