### ISSUE TITLE
Private field '#head' must be declared in an enclosing class

### ISSUE THREAD

**Issue by justinr1234** [isaacs/node-lru-cache#315]
https://github.com/isaacs/node-lru-cache/blob/870a66deb10fb1a8ecd242ea960465fd3232bac9/src/index.ts#L930

In the web browser (nextjs), this is throwing an error `Private field '#head' must be declared in an enclosing class`

**Comment by isaacs** [comment]
But... it _is_ declared in an enclosing class.

This works just fine, logs `2 0 1` in any modern browser:

```html
<!DOCTYPE html>
<html>
  <head>
    <script type="module">
      import { LRUCache } from 'https://unpkg.com/lru-cache@10.0.1/dist/mjs/index.js'
      const cache = new LRUCache({ max: 3 })
      cache.set('one', 1)
      cache.set('two', 2)
      cache.set('tre', 3)
      cache.get('two')
      const internals = LRUCache.unsafeExposeInternals(cache)
      console.log(cache.get('two'), internals.head, internals.tail)
    </script>
  </head>
</html>
```

Idk what next is doing to LRUCache, but it's not correct.

**Comment by justinr1234** [comment]
I was using an old version of the library via octokit
