### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by byronmwong** [isaacs/node-lru-cache#32]
I ran into an IE bug when using LRUCache with numeric keys.

The bug is documented [here](http://webreflection.blogspot.com/2014/04/all-ie-objects-are-broken.html). Here's the important part:

> All IEs that support `Object.create` seem to be affected. If there are only numeric properties in the created object and no `new` keyword has been used to initialize the same, hasOwnProperty check as well as isPropertyEnumerable will miserably fail.

The bug affects LRUCache's `hOP` check during `LRUCache.prototype.set`. In IE, if I only have numeric keys and try to set with an existing key, `set` will think that the key doesn't yet exist and create a new entry instead of overwriting the existing entry.

There are a couple ways we can get around this

1 Modify `hOP` to use the `in` operator. This is safe because `hOP` is only used on `this._cache` and `this._cache` has no prototype.

```
function hOP (obj, key) {
  return key in obj;
}
```

2 Modify the creation of `this._cache`. If we set a configurable numeric property and then delete it, the object will then behave correctly.

```
function makeObject() {
  var obj = Object.create(null);
  delete Object.defineProperty(obj, 0, {configurable: true})[0];
  return obj;
}
```

@isaacs do you have any preference on which fix to apply? `2` seems like the safer route, since `hOP`'s behavior will be unchanged. There won't be much of a performance hit since objects are only created in `LRUCache.prototype.reset`. I'm happy to open a PR.

**Comment by isaacs** [comment]
This should be irrelevant as of version 3.0.  It's using the `pseudomap` module in engines that don't support `Map` natively, and that module prefixes all keys with a `_` character.

**Comment by byronmwong** [comment]
Great, thanks for the update!
