### ISSUE TITLE
ERR_REQUIRE_ESM on AWS Lambda with Node 18.x

### ISSUE THREAD

**Issue by a-tortevois** [isaacs/node-lru-cache#328]
Hello, 
I'm using a lib which have this dependencies chain:
```
mylib > glob > path-scurry > lru-cache
mylib > glob > path-scurry > minipass
```
on a AWS lamba function written in CommonJS (no `"type":"module"` in the package.json)

I'm facing this error:
```
"errorMessage": "require() of ES Module /var/task/node_modules/path-scurry/node_modules/lru-cache/dist/commonjs/index.js from /var/task/node_modules/path-scurry/dist/cjs/index.js not supported.\n/var/task/node_modules/path-scurry/node_modules/lru-cache/dist/commonjs/index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which declares all .js files in that package scope as ES modules.\nInstead either rename /var/task/node_modules/path-scurry/node_modules/lru-cache/dist/commonjs/index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change \"type\": \"module\" to \"type\": \"commonjs\" in /var/task/node_modules/path-scurry/node_modules/lru-cache/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).\n",
    "code": "ERR_REQUIRE_ESM",
    "stack": [
        "Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/path-scurry/node_modules/lru-cache/dist/commonjs/index.js from /var/task/node_modules/path-scurry/dist/cjs/index.js not supported.",
        "/var/task/node_modules/path-scurry/node_modules/lru-cache/dist/commonjs/index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains \"type\": \"module\" which declares all .js files in that package scope as ES modules.",
        "Instead either rename /var/task/node_modules/path-scurry/node_modules/lru-cache/dist/commonjs/index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change \"type\": \"module\" to \"type\": \"commonjs\" in /var/task/node_modules/path-scurry/node_modules/lru-cache/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).",
        "",
        "    at Object.<anonymous> (/var/task/node_modules/path-scurry/dist/cjs/index.js:27:21)",
```

To solve it, I try to remove manually the `"type":"module"` in the files:  
`path-scurry/node_modules/lru-cache/package.json`
`path-scurry/node_modules/minipass/package.json`
... and it works.

Unfortunately, my lambda is deployed automatically from a CI/CD and I can't modify these files automatically.

According to this article : https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

It seems a good solution to remove it from this `package.json` and also from `minipass/package.json`
Or do you have another idea ?

**Comment by isaacs** [comment]
What version of node is this? Because it's lying, the nearest package.json to that file is at dist/commonjs/package.json.

**Comment by a-tortevois** [comment]
I'm using node 18.x, available on AWS.

**Comment by isaacs** [comment]
It's not node 18, or it's not those packages (maybe lambda js mutating them somehow?) because if it was, it'd be working.

I'm not going to remove the `type:"module"`, because that's what's working now in every other scenario. It's a hybrid package, it works as either esm or cjs, using the package.json files in dist to set the module type, and `exports` to load the appropriate module depending on whether import or require are used.

**Comment by isaacs** [comment]
The article linked is essentially the same approach that [tshy](https://github.com/isaacs/tshy) uses, which is what i use to build this package.

**Comment by a-tortevois** [comment]
Ok, thanks for your reply.
I was not aware that conditional exports are a standard feature https://nodejs.org/api/packages.html#conditional-exports
Sorry for the inconvenience
