### ISSUE TITLE
./min exports files are missing since v10.0.2

### ISSUE THREAD

**Issue by bluwy** [isaacs/node-lru-cache#334]
Since v10.0.2, the `./min` exports files are missing. v10.0.1 has the files. [GitHub diff between v10.0.1 and v10.0.2](https://github.com/isaacs/node-lru-cache/compare/v10.0.1...v10.0.2).

Personally I'm not using this library nor the specific export, but I found this from https://publint.dev/lru-cache@10.0.2 as `lru-cache` is a popular npm package.

I think the issue is because `fixup.sh` is not called before publish. Or `package.json` `tshy.exports` doesn't match `exports`?

**Comment by isaacs** [comment]
Oh, whoops, I thought fixup.sh was just doing the hybrid stuff, forgot about the minification. Will fix.

**Comment by bluwy** [comment]
Hey, it seems like it's still not quite fixed yet on v10.2.1 (latest). The `.min.js` files aren't published: https://www.npmjs.com/package/lru-cache?activeTab=code

https://publint.dev/lru-cache@10.2.1
<img width="797" alt="image" src="https://github.com/isaacs/node-lru-cache/assets/34116392/9379ebf9-1c15-449c-94c5-c33e5971bf63">
