### ISSUE TITLE
Why has Node.js changed since version 10.x without a major version update?

### ISSUE THREAD

**Issue by czewail** [isaacs/node-lru-cache#341]
https://github.com/isaacs/node-lru-cache/blob/e01135c4270941ac54d00a6b96eefdca31f3a6f6/package.json#L71

This directly caused my application to be unable to install.

im use nodejs v16.17.0

**Comment by headless-kjh** [comment]
The same issue is occurring. It appears to be a syntax error.

**Comment by ryanlonstein** [comment]
Had the same issue, but looks like they released a new patch version to fix it!

**Comment by lucas200631** [comment]
My project uses version v10.2.0, why version 10.4.2 & 10.4.1 change node limit ，appacting our node limit?

**Comment by wraithgar** [comment]
Even the current setting `{ node: '14 || 16 || 18 || 20 || >=22' }` is a semver-incompatible change with what was in `10.3.0` `{ node: '14 || >=16.14' }`

This is gonna be quite a headache for the npm cli packages that have things like `>=18.0.0` declared for their upper-bounds in engines.
