### ISSUE TITLE
Restore support for LTS versions

### ISSUE THREAD

**Issue by Mister-Hope** [isaacs/node-lru-cache#343]
See https://nodejs.org/en/about/previous-releases, node 18 is a valid LTS version till June 2025, so unless there are strong reasons that you must drop it, you'd better support it.

While I did not find any, this package could probably run on node18 while you are dropping it for no reason.

**Comment by kachkaev** [comment]
I agree. [Node 18 is still gonna be an official LTS](https://github.com/nodejs/Release) for nine months:

![Screenshot 2024-07-13 at 21 23 40](https://github.com/user-attachments/assets/1da15fd3-73c0-477a-8cae-a6ed77db7aae)

A lot of libraries depend on `lru-cache` and if they upgrade to v11, they will unwillingly run into problems.

**Comment by isaacs** [comment]
They won't upgrade to v11 by accident, because it's semver major. 

Please stop sending this identical pr to all my repos. I chose the engines restriction deliberately.

**Comment by kachkaev** [comment]
> I chose the engines restriction deliberately.

What’s the motivation behind your choice? What is wrong in the currently supported Node v18 that it can no longer be supported by `lru-cache`?

These questions are driven by curiosity and a desire to understand your thinking. The library is downloaded ≈175M times a week so I guess I’m not the only one who would benefit from the answer.

**Comment by isaacs** [comment]
Anyone on node 18 can keep using the previous major forever. That's fine. It's only the new version that requires a newer node. 

The importer/loader behavior changed dramatically in node 20. It's too much of an annoying hassle to support both in my tests, since I use a bunch of tooling which touches that interface.

**Comment by Mister-Hope** [comment]
（╯－＿－）╯╧╧

# 👎

Then I see, it is just personal taste.  Just like you said in another reply note 18 is dead to you, no matter whether it's at a community.

You don't care about the community and the node ecosystem. 

I've read all your major changes across all your packages and I didn't find anything that stops you supporting node18, while you still insist that you don't want to support it.

So it's not too hard to understand that all your project are mostly working by your own. :)  Conversations over, have a nice life with your own.

**Comment by isaacs** [comment]
> You don't care about the community and the node ecosystem.

Wow. 

Feel free to not use the libraries I've created, if you can. After all, you've paid nothing for my labor, and are entitled to none of it.

Your ignorance and entitlement are astounding.
