### ISSUE TITLE
Be able to auto dispose if system memory low?

### ISSUE THREAD

**Issue by Mrgaton** [isaacs/node-lru-cache#344]
How i can auto dispose the allocated entries automatically if the memory is full.

**Comment by isaacs** [comment]
This library doesn't do any kind of detection of your system memory. It just lets you set a max and then it keeps it below that count of items. It's up to you to decide how much you want to cache.

**Comment by Mrgaton** [comment]
I have an http server and I transform the data on the fly and then I cache It using your cache cause my server is so slow that transforming the data takes almost minutes, but the problem is that I have 1 gig of ram so this would be grateful for me. But I guess I'll just check the ram before saving new item and done thanks.

**Comment by isaacs** [comment]
Or just do some basic math. How much storage is incurred for one item? Divide that into the amount of space you have to work with, and set that number as the lru-cache max. You probably shouldn't be repeatedly checking the memory usage at run-time, that's almost certainly going to make things slower.
