### ISSUE TITLE
Mocking lru-cache TTL with vitest not working

### ISSUE THREAD

**Issue by eakl** [isaacs/node-lru-cache#345]
Using vitest, I manage to mock Date.now

```ts
it('should advance time', () => {
         const date = Date.now()
         vi.setSystemTime(date)

         vi.advanceTimersByTime(10)
         expect(Date.now()).toEqual(date + 10) // true

         vi.advanceTimersByTime(9)
         expect(Date.now()).toEqual(date + 19) // true

         vi.advanceTimersByTime(10)
         expect(Date.now()).toEqual(date + 29) // true
      })
```

But it has no effect on lru-cache TTL. Vitest controlled timers doesn't seem to affect LRU timer.

```ts
it('should expire ttl', () => {
         const lru = new LRUCache({ max: 10, updateAgeOnGet: false })

         const date = Date.now()
         vi.setSystemTime(date)

         lru.set('key', 1234, { ttl: 10 })

         vi.advanceTimersByTime(9) // advance time by 9 ms
         console.log(lru.getRemainingTTL('key')) // remaining ttl is still 9.xx ms, no effect on cache-lru clock
         expect(lru.get('key')).toBe(1234)

         vi.advanceTimersByTime(2) // advance time by 2 more ms, total 11
         console.log(lru.getRemainingTTL(1)) // remaining ttl is still 9.xx ms
         expect(lru.get(1)).toBeUndefined() // AssertionError: expected 1234 to be undefined
      })
```

**Comment by isaacs** [comment]
That's because `lru-cache` uses performance.now(), not Date.now(). Maybe check out [clock-mock](http://npm.im/clock-mock), which I use to test lru-cache myself.

**Comment by eakl** [comment]
It works with `mock-clock` but not with vitest (even after adding support to `performance` and passing tests successfully on `performance.now()`).  Thanks @isaacs

**Comment by jawadst** [comment]
`lru-cache` TTLs cannot be tested with standard sinon/vitest clock mocks because `lru-cache` keeps its own reference to the `performance` object at https://github.com/isaacs/node-lru-cache/blob/main/src/index.ts#L7:

```
const perf: Perf =
  typeof performance === 'object' &&
  performance &&
  typeof performance.now === 'function'
    ? performance
    : Date
```

sinon/vitest replace the `performance` object but that has no effect on `lru-cache` that still uses the old reference.

@isaacs Would you be open to changing that behavior so that `lru-cache` can be tested with common libraries like Sinon?

One option would be to make that check a function so that `performance` is resolved every time:

```
const perf: Perf = () =>
  typeof performance === 'object' &&
  performance &&
  typeof performance.now === 'function'
    ? performance
    : Date
```

**Comment by edward-simpson** [comment]
Don't quite agree that having to import a package a different way to standard is a good solution, I've never come across having to do this with any other package, and it was a bit of a pain to debug, but who am I to argue with the creator of npm lol

At very least this could do with being mentioned in the docs, I'll pop a PR together if you don't mind

**Comment by edward-simpson** [comment]
@isaacs It looks like with this change, I run into some other issues - `jest.useFakeTimers()` initially means `performance.now() === 0`, which then means `!!s` is false in `isStale`, as `starts[index]` remains as `0` when `setItemTTL` gets run:

```
    this.#isStale = index => {
      const s = starts[index]
      const t = ttls[index]
      return !!t && !!s && (cachedNow || getNow()) - s > t
    }
```

The quick solution is to advance timers by 1ms immediately after mocking

```
    jest.useFakeTimers()
    jest.advanceTimersByTime(1)
```

But as before, this isn't immediately obvious.  I appreciate that we'd now be modifying the package further purely for testing purposes...
