### ISSUE TITLE
Backport type fixes from v11.0.1 to v10

### ISSUE THREAD

**Issue by wolfy1339** [isaacs/node-lru-cache#355]
When using `LRUCache` with TypeScript 5.6.2 the build spits out warnings

```
Error: node_modules/lru-cache/dist/esm/index.d.ts(1032,5): error TS2416: Property 'forEach' in type 'LRUCache<K, V, FC>' is not assignable to the same property in base type 'Map<K, V>'.
```

lru-cache 10.4.3
Node 18
TypeScript 5.6.2

Ref: https://github.com/octokit/auth-app.js/pull/644

**Comment by wolfy1339** [comment]
```
Error: node_modules/lru-cache/dist/esm/index.d.ts(1032,5): error TS2416: Property 'forEach' in type 'LRUCache<K, V, FC>' is not assignable to the same property in base type 'Map<K, V>'.
  Type '(fn: (v: V, k: K, self: LRUCache<K, V, FC>) => any, thisp?: any) => void' is not assignable to type '(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any) => void'.
    Types of parameters 'fn' and 'callbackfn' are incompatible.
      Types of parameters 'map' and 'self' are incompatible.
        Type 'LRUCache<K, V, FC>' is not assignable to type 'Map<K, V>'.
          The types returned by 'entries().next(...)' are incompatible between these types.
            Type 'IteratorResult<[K, V], void>' is not assignable to type 'IteratorResult<[K, V], undefined>'.
              Type 'IteratorReturnResult<void>' is not assignable to type 'IteratorResult<[K, V], undefined>'.
                Type 'IteratorReturnResult<void>' is not assignable to type 'IteratorReturnResult<undefined>'.
                  Type 'void' is not assignable to type 'undefined'.
```

**Comment by AviVahl** [comment]
this already got fixed in v11.0.1 by the following commit:
https://github.com/isaacs/node-lru-cache/commit/5ed947ddc8a26b5f2727f9c66f0ef835a9ede0db

problem is... deps out there cannot upgrade to v11 without dropping Node 18... which some still support.
e.g. https://github.com/probot/probot/pull/2057

@isaacs any chance this fix can be backported to v10 as well?

**Comment by isaacs** [comment]
No. Turn on `skipLibCheck: true` in your tsconfig, as recommended by Microsoft's official TypeScript documentation.

**Comment by isaacs** [comment]
Or just don't upgrade TypeScript until you're ready to upgrade node. Or fork this library. Or copy it into your `lib` folder and make whatever changes you want to it. Really, you have so many options, the license is incredibly liberal.

**Comment by AviVahl** [comment]
> No. Turn on `skipLibCheck: true` in your tsconfig, as recommended by Microsoft's official TypeScript documentation.

Turning type checking globally off for .d.ts files would hide the issue, yes. It would also potentially hide many other issues, some of which we've my team experienced  in the past.

> Or just don't upgrade TypeScript until you're ready to upgrade node. Or fork this library. Or copy it into your `lib` folder and make whatever changes you want to it. Really, you have so many options, the license is incredibly liberal.

We're indeed using latest LTS Node. it's third parties which still need/want to support Node 18. Considering 18 is not EOL, I believe this to be reasonable.

Forking the library would not do us much good, as it's used by a third party. Forking two libraries just to remove `implements Map` from a .d.ts file seems like an overkill.

Seeing most of the millions of [downloads](https://www.npmjs.com/package/lru-cache?activeTab=versions) this library had in the past week is of v10, and some of those use typescript without disableLibCheck, I'd kindly ask you to reconsider.

**Comment by isaacs** [comment]
You're not the first to ask, but I won't reconsider, sorry. The answer is the same, regardless of the number of people asking.

It's unrewarding work, so I won't do it for free. But for $500/month subscription, I will gladly maintain a legacy version of this library indefinitely, and back port whatever fixes or improvements are possible to be ported in nonbreaking ways.

**Comment by isaacs** [comment]
Or, just don't upgrade TS until you can upgrade node. Like, this is not a challenging puzzle to solve.
