### ISSUE TITLE
get -> shiftLU -> delete cause performance issue

### ISSUE THREAD

**Issue by dead-horse** [isaacs/node-lru-cache#36]
every get operator need execute a delete [here](https://github.com/isaacs/node-lru-cache/blob/master/lib/lru-cache.js#L229).

this cause a serious performance issue. also spent a lot of time in GC.

**Comment by isaacs** [comment]
It's been a year now, and this module has seen a lot of upgrades.  Can you try on version 3.x and see if you still have problems?  Thanks.
