### ISSUE TITLE
package.json must be actual JSON, not just JavaScript

### ISSUE THREAD

**Issue by xdemocle** [isaacs/node-lru-cache#39]
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.4
npm ERR! file /Users/democle/.npm/lru-cache/2.5.0/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected end of input
npm ERR! File: /Users/democle/.npm/lru-cache/2.5.0/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by oneiljm** [comment]
Many thanks........!!!

**Comment by aholtry** [comment]
Saved my day! Thank you.

**Comment by Steve001** [comment]
Well...it didn't worked for me ....maybe it's come from my bad coding...

**Comment by isaacs** [comment]
Locking this conversation.  It's a >2 year old bug.  Even if you are getting the same error, it's likely for a different reason.
