### ISSUE TITLE
option to set maxAge on a cache key

### ISSUE THREAD

**Issue by bradoyler** [isaacs/node-lru-cache#42]
Right now the maxAge is setup on the options of the lru-cache instance. 
Would it be useful to specify the maxAge when doing a set? ie. `LRU.set('key', 'value', 3000)`

**Comment by homerjam** [comment]
+1

**Comment by apechimp** [comment]
It looks like this is actually [how it works](https://github.com/isaacs/node-lru-cache/blob/master/lib/lru-cache.js#L150) already. The documentation just needs to be updated.

**Comment by bradoyler** [comment]
Sorry. Outdated issue.
