### ISSUE TITLE
The method get doesn't update the "recently used"-ness of the key as the doc says

### ISSUE THREAD

**Issue by felipou** [isaacs/node-lru-cache#43]
The documentation says (under the get and set methods):

`Both of these will update the "recently used"-ness of the key. They do what you think.`

But the `get` method doesn't update the element age. I checked the source code, and the `now` attribute of the `hit` isn't updated. I made this simple test code to check and confirm this:

```
var LRU = require("lru-cache");

var cache = LRU( {
    max: 100,
    maxAge: 10000
} );

cache.set( "1234", 1 );

setTimeout( function() {
    cache.set( "1234", 2 );
    console.log( "testing after 5s: " + cache.get( "1234" ) );
}, 5000 );

setTimeout( function() {
    console.log( "testing after 9s: " + cache.get( "1234" ) );
}, 9000 );

setTimeout( function() {
    console.log( "testing after 11s: " + cache.get( "1234" ) );
}, 11000 );

setTimeout( function() {
    console.log( "testing after 16s: " + cache.get( "1234" ) );
}, 16000 );
```

If the `get` method updates the age of the key, shouldn't the last timeout (16s) print the value `2` again instead of `undefined`?

**Comment by isaacs** [comment]
Yep, thanks.  Fixed in master.

**Comment by felipou** [comment]
Great! Thanks for this awesome package! :)

**Comment by isaacs** [comment]
So, it turns out that this was always by design.

`hit.now` is supposed to be when the thing is set, not when it's retrieved.  Otherwise, you can keep getting stale entries forever when there's a maxAge.

**Comment by felipou** [comment]
I thought that was the intended purpose, since there is a `has` method and there is no other way to update the `hit.now` attribute.

Anyway, if that's the way that the `get` method is supposed to work, the documentation should be updated, and I believe there should be some method (`update`, perhaps?) to update the "recently used"-ness of the key (the `hit.now`), without having to call `set`, because calling `set` forces the `dispose` method to be called on the element, which is not always desired.

Or maybe an option that determines if `hit.now` is supposed to be updated when `get` is called?

**Comment by felipou** [comment]
I just re-read the docs and the code, and I believe I was mixing up concepts. One thing is the age and another is the "recently used"-ness of the key, right?

But it feels a bit strange that the key is updated on the list of "recently used"-ness, but it's age stays the same, no? That way, the most recently used item can expire of old age, while items that were used a long time ago still are young of age. I understand that this is the intended way, but shouldn't there be some flexibility to allow for other interpretations of the age of the key?

Anyway, I think the docs should elaborate a little more on the difference between the age and the "recently used"-ness of the key. If you want, I could try to help with that.

**Comment by CoDEmanX** [comment]
What's the status on this one?
Recently **re**-used entries should not die of old age IMO.

**Comment by isaacs** [comment]
Let's say you have a cache that is sitting in front of a database.  The database entries change, on average, every few minutes or so, and when users edit an entry, they go to the page for that entry and hit refresh until it shows up.  (This is typical user behavior for verifying that an edit "takes" on the site.)

So, you view your post (entry gets into cache, with `hit.now` set to a time that we'll call `t=0s`).  Oops, a typo!  Go to the edit page, update the db.  Return to the page.  The maxAge is 300s, but the post is only 60s old.  Hit refresh.  Now the age is 120s old, still cached, and it's the most recently used item.  Hit refresh again.  Now it's 180s old, still cached, still at the top of the recently used stack.  Again, now time = 240s.  Still cached.  Hum a little song about patience, hit refresh again, this time at t=314s.

Now, it's still the most recently used item, but the cache says, "Even though this has been gotten again and again, and is very recently used, it's also 314s old, and my maxAge is 300s.  So, even though this is a highly requested item, it's _too old_ so I'm going to treat it as a cache miss."  The application sees this cache miss and updates the data fresh from the backend source (the database).

The user sees their edited content, calms down, and does not email support about this incident.

There are of course ways to preemptively invalidate a cache, but that requires signaling from the DB that it's changed, and it's not always worth the complexity.

If you do not want recently re-used items from dying of old age, *don't set a maxAge on your cache*, it's as simple as that.  The maxAge means "the maximum amount of time that anything can sit in the cache".  It's specifically intended as a way to invalidate old/stale items that _are_ being requested frequently, as in the above example.

**Comment by isaacs** [comment]
Note: "Recently used"-ness of an item is determined by the various mru/lru counters and arrays, not by `hit.now`.  That's not date-based, it's just ordinal.  The only way for lru-cache to know about time at all is if maxAge is being used.

**Comment by CoDEmanX** [comment]
Thanks for the in-depth explanation. I can totally see why one would want an entry to age even if it was used very recently. My use case is just different: a deterministic function is used to compute a value, and that value is cached, using the function input as key. Because of the determinism, the same input will always result in the same value and thus no key is ever used again unless for the very same input. The attribute value can't change without the key changing too. I'll leave out the magAge then.

**Comment by isaacs** [comment]
@CoDEmanX Exactly, your cache entries are immortal, and you can use lru-cache to just keep the last X number of them that have been computed.  If it's a large solution space, and you expect a small number of keys to be repeatedly requested rapidly, and they are costly to compute, then this module could help you a lot.

**Comment by CoDEmanX** [comment]
They are not *that* costly to compute (RegExp), but a cache will definitely improve the performance. It is very likely that the same input string is passed to a function in a short amount of time, and unlikely to occur again after that:

http://stackoverflow.com/questions/32397729/partial-garbage-collection-of-objects-possible-server-side-js

I could probably set a maxAge of a couple minutes for my purpose, it shouldn't really matter. But I don't know how users will actually do in their queries.
