### ISSUE TITLE
Using maxAge does not check for item's age. It checks for last access time.

### ISSUE THREAD

**Issue by tmarciszewski** [isaacs/node-lru-cache#45]
I'm not sure if this is intended behaviour. Up to version 2.5.0 setting maxAge caused removal of item from cache after maxAge milliseconds. At the moment the check is not made against total age of item but against its last access date. 

This means that cached item can be stored indefinately if they are accessed often. Item will be removed only if it's accessed after time greater than maxAge.

Is this intended behaviour? If it is it should be made clear in the documentation.

**Comment by isaacs** [comment]
Oh, no, you're right.  That's a mistake.  At least, it was a breaking change that I didn't notice.  My apologies.  I'll fix on 2.6.2.

**Comment by tmarciszewski** [comment]
That's great. Thanks.
