### ISSUE TITLE
Set cache entries to undefined instead of deleting them?

### ISSUE THREAD

**Issue by CoDEmanX** [isaacs/node-lru-cache#52]
Wouldn't it be faster if you did

    self._cache[ hit.key ] = undefined

instead of 

    delete self._cache[ hit.key ]

here? https://github.com/isaacs/node-lru-cache/blob/master/lib/lru-cache.js#L254

It might require an additional !== undefined check in other places, but other than that, it is said to be faster than delete:

http://stackoverflow.com/a/21735614/2044940

**Comment by isaacs** [comment]
It is said, not proven. 

The problem there is that the key list can get quite large, and only delete mitigates that explosion.

**Comment by CoDEmanX** [comment]
But setting it to undefined will make it eligible for garbage collection, unless there are still references hold somewhere else - which shouldn't be the case here.

**Comment by isaacs** [comment]
Deleting breaks the link just as surely.

Try this:

```
var N = 100000
var o = {}
for (var i = 0; i < N; i++) {
  o['key-' + i] = true
  o['key-' + i] = undefined
}
console.log(Object.keys(o))
```

vs:

```
var N = 100000
var o = {}
for (var i = 0; i < N; i++) {
  o['key-' + i] = true
  delete o['key-' + i]
}
console.log(Object.keys(o))
```

If you ever have to traverse the list of keys, delete is a better choice, because it removes the key as well as the value.

**Comment by isaacs** [comment]
```
time node k.js
  ... many keys ...
  'key-99985',
  'key-99986',
  'key-99987',
  'key-99988',
  'key-99989',
  'key-99990',
  'key-99991',
  'key-99992',
  'key-99993',
  'key-99994',
  'key-99995',
  'key-99996',
  'key-99997',
  'key-99998',
  'key-99999' ]

real	0m0.863s
user	0m0.509s
sys	0m0.067s

$ time node d.js
[]

real	0m0.192s
user	0m0.165s
sys	0m0.024s
```

**Comment by CoDEmanX** [comment]
I assume d.js uses delete?

**Comment by isaacs** [comment]
Yes, exactly.
