### ISSUE TITLE
Using objects as cache keys

### ISSUE THREAD

**Issue by tedpennings** [isaacs/node-lru-cache#53]
As I'm sure you know, using objects as cache keys causes a 100% collision rate for all object keys. All object keys are stored with a key `[object Object]` and therefore resolve to the same value.

Would you be open to a PR to allow users to specify objects as cache keys?  

We could use an array as the underlying store, for the object section or for the whole cache (slower). Here's the basic implementation I'd add:

```javascript
const cacheArray = []

function get(key) {
  const hit = cacheArray.find(elem => elem.key === key)
  if (hit) {
    // LRU staleness and touch logic here
    return hit.value
  }
  return false
}

function set(key, value) {
  cacheArray.push({key, value})
  // LRU eviction logic here
}
```

If you don't want to do this, no worries, but I'd love to send README PR to mention that cache keys should not be an object (or array).

**Comment by isaacs** [comment]
Using an array instead of an object, and replacing O(1) lookups with O(n) lookups is really not a good choice.

I'd prefer a PR to throw a TypeError if the key is not a string.

We could use a Map or Set (or even WeakMap) in some interesting ways, but it would be (a) a rewrite, and (b) not backwards-compatible to Node 0.10 and before.

**Comment by tedpennings** [comment]
Ok cool, when would you want the TypeError to be thrown?  If someone uses an object key, always raise, or only raise if `key.toString() === '[object Object]'`  ? 

The more I think about it, the more I'm concerned about backwards compatibility and the performance cost of determining if someone is using an invalid key. If you define a custom `toString` method for your key objects, I think the cache would work fine, as that `toString` method could reflect the object/key identity. There would be some cost to running `key.toString() === '[object Object]'`, but that same price would be paid for each call to `this._cache[key]`, so we could actually make ` this._cache[key]` faster by setting `key = key.toString()` in the case of object keys.

So yeah, I'm leaning toward using `warning.js` to check key validity. I'll can work up a PR for that.

As far as fixing my original issue, yeah, WeakMap would do it (or maybe `Symbol.key()`), but it would have browser compatibility problems I'd rather avoid. The difference between O(1) and O(n) is trivial because because N is always < 20 for me. In the place I ran into this issue, my cache is capped at 3  (huge) items.

**Comment by isaacs** [comment]
`if (typeof key !== 'string') throw new TypeError('key must be a string')`

Just liberally throw that in every function that takes a key, and add some
tests using `t.throws`.

The backwards compatibility isn't really an issue, since non-string keys
cause undefined (or at best, poorly defined) behavior now, and the code all
assumes keys are strings.

If you don't wanna send a PR, I'll get to it eventually. Thanks :)

**Comment by tedpennings** [comment]
We can continue this in #59

**Comment by nicojs** [comment]
@isaacs this is clearly not backward compatible and it is killing our build. This typecheck change should be a new major version. Could you please put the code back and release a new 2.7.x version? 

```
Stack trace:
TypeError: key must be a string or number. undefined
    at typeCheckKey (/var/build/jenkins/jobs/antares-angular/workspace/node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:18:11)
    at LRUCache.get (/var/build/jenkins/jobs/antares-angular/workspace/node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:227:3)
    at /var/build/jenkins/jobs/antares-angular/workspace/node_modules/grunt-bower-install-simple/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
```
In short: we are using a fixed version of grunt-bower-install-simple, which is using a fixed version of bower. However, bower is fixed on the minor releases of the lru-cache
```
    "lru-cache": "^2.5.0",
```
There apparently is some miss use of the LRU cache API. In any case: this type check change should be a major change.

**Comment by balinterdi** [comment]
Same here, see my comment on https://github.com/isaacs/node-lru-cache/pull/59.
