### ISSUE TITLE
Breaking change in 2.7.1

### ISSUE THREAD

**Issue by jakepusateri** [isaacs/node-lru-cache#60]
I am getting the following error on 2.7.1 when calling `has(undefined); `
```
.../node_modules/lru-cache/lib/lru-cache.js:18
    throw new TypeError("key must be a string or number. " + typeof key)
```
While it makes sense to throw now, it did not throw in 2.7.0.
Should this be a major release instead?

More detailed log
```
jacobp:/tmp
$ npm i lru-cache@2.7.0
lru-cache@2.7.0 node_modules/lru-cache
jacobp:/tmp
$ node
> var cache = require('lru-cache')(10)
undefined
> cache.has(undefined)
false
> 
(^C again to quit)
> 
jacobp:/tmp
$ npm i lru-cache@2.7.1
lru-cache@2.7.1 node_modules/lru-cache
jacobp:/tmp
$ node
> var cache = require('lru-cache')(10)
undefined
> cache.has(undefined)
TypeError: key must be a string or number. undefined
    at typeCheckKey (/private/tmp/node_modules/lru-cache/lib/lru-cache.js:18:11)
    at LRUCache.has (/private/tmp/node_modules/lru-cache/lib/lru-cache.js:217:3)
    at repl:1:7
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
> 
```

**Comment by bradb** [comment]
We are experiencing this issue as well. Is there a workaround to lock the version to 2.7.0 by any chance, when bower tries to install it?

**Comment by vladikoff** [comment]
roll back please!

**Comment by sheerun** [comment]
Please revert. Bower's users are suffering.

**Comment by nicojs** [comment]
@isaacs this is clearly not backward compatible and it is killing our build. This typecheck change should be a new major version. Could you please put the code back and release a new 2.7.x version?

Stack trace:
```
TypeError: key must be a string or number. undefined
    at typeCheckKey (/var/build/jenkins/jobs/antares-angular/workspace/node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:18:11)
    at LRUCache.get (/var/build/jenkins/jobs/antares-angular/workspace/node_modules/grunt-bower-install-simple/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:227:3)
    at /var/build/jenkins/jobs/antares-angular/workspace/node_modules/grunt-bower-install-simple/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
```
Bower defines the 2.x version of lru cache:
    "lru-cache": "^2.5.0",

**Comment by dlo83** [comment]
:+1:

**Comment by dlo83** [comment]
![make](https://cloud.githubusercontent.com/assets/1965272/11373267/65278958-929f-11e5-8fa0-e8756b426a3f.png)

**Comment by vladikoff** [comment]
Update to Bower 1.6.x or 1.5.4 or 1.4.2 to fix this issue.

**Comment by goyalvarun601** [comment]
Updating to 1.4.2 works for me.

**Comment by isaacs** [comment]
So, you want to be able to do `cache.has(undefined)`?  That's the issue?

I think it's still a bad idea to allow non-string keys for `set` and `get`.

**Comment by vladikoff** [comment]
@isaacs thanks for the update!

**Comment by isaacs** [comment]
Note that now `cache.set("undefined", 123); cache.get()` would return `123`, because the undefined key would be stringified.

Now, any get/has/del/peek operation with a non-string/number key will return undefined and be a no-op.

**Comment by nicojs** [comment]
@isaacs I don't think the issue was that we *want* ```cache.has(undefined) ``` to work, its just that it was a breaking change and deserved its own major version.

**Comment by isaacs** [comment]
Updated to just make this a warning, albeit a pretty forceful one with a stack trace.
