### ISSUE TITLE
2.7.2 breaks backwards compatibility

### ISSUE THREAD

**Issue by palmerabollo** [isaacs/node-lru-cache#61]
With lru-cache@2.7.0 this code works. It stores an object in the cache using a mongo ObjectID as key:

```js
var LRU = require('lru-cache');
var ObjectID = require('mongodb').ObjectID;

var cache = LRU();
var key = new ObjectID();
cache.set(key, {}) // works fine
```

Something changed in lru-cache@2.7.2 that broke backwards compatibility, as now the call to `cache.set` complains about the key not being a string:

```js
TypeError: key must be a string or number. object
    at typeCheckKey (..node_modules/lru-cache/lib/lru-cache.js:18:11)
    at LRUCache.set (...node_modules/lru-cache/lib/lru-cache.js:171:3)
    at repl:1:7
    ...
```

This new behaviour sounds reasonable to me, but I think it should be fixed in a major release (not in 2.7.x), as it breaks backwards compatibility. What do you think?

I'm using node 4.2.1 if that helps.

**Comment by isaacs** [comment]
You do realize that this is already a bug in your program?

If the key is an object, then the effective key value is a stringified version of that object, not the object itself.

So, for example:

```
var a = {}
var b = {}
var cache = LRU()
cache.set(a, 'this is a')
cache.set(b, 'this is b')
cache.get(a) // 'this is b' 
```

How would you like to handle this situation?  Failing silently is not really good, and the feedback from it tells me that a lot of people using this module are probably introducing weird bugs with it.

**Comment by isaacs** [comment]
Updated to just make this a warning, albeit a pretty forceful one with a stack trace.

**Comment by palmerabollo** [comment]
Thanks isaacs. Yes, I agree, even when that's not the case with an ObjectID. The new behaviour (fail if the key is not a string/number) is right and it should be the default, but we should follow semver and change that behaviour in 3.x as breaks backwards compatibility.
