### ISSUE TITLE
proactive pruning

### ISSUE THREAD

**Issue by mbroadst** [isaacs/node-lru-cache#62]
The documentation indicates that given a `maxAge` "Items are not pro-actively pruned out as they age". Are there any plans to provide such behavior? Has anyone been able to implement this easily with the existing implementation?

**Comment by mbroadst** [comment]
It seems like it would be easy enough to implement an internal timer to iterate over the cache checking `isStale` on entries pruning them as needed. Would there be any interest in incorporating this into the module, or does it feel out-of-scope for the intended use cases?

**Comment by isaacs** [comment]
It would be tricky to get the heuristics right. In some cases, pruning will be more expensive than it's worth. It also conflicts with the `allowStale` behavior. 

It could be optional, and let the user provide the pruning interval. Make sure to unref the timer so it doesn't keep the process open forever. Patch welcome with test and docs. The default should still be no pruning.

**Comment by mbroadst** [comment]
@isaacs perhaps the easiest way to support this on my side is to provide a top level method called `prune` which does the actual internal pruning based on the time `prune` was called. This way, if a user wants to implement pro-active pruning, they simply need creating their own timer and periodically call `prune`?

**Comment by isaacs** [comment]
@mbroadst Sure, that sounds like a reasonable approach.

**Comment by dotcypress** [comment]
:+1:

**Comment by isaacs** [comment]
Done in #64, landed on master and pushed on v4
