### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by calebmer** [isaacs/node-lru-cache#66]
I'm hesitant to use this module when there are no performance tests. How well does this module compare to other lru implementations? Another one I am looking at is [js-lru](https://github.com/rsms/js-lru).

**Comment by isaacs** [comment]
v7 performs very well.  v6 and before, not great, kinda middle of the pack for some use cases, bottom for others. 

See https://github.com/dominictarr/bench-lru/pull/41
