### ISSUE TITLE
Patch welcome: Use -1 as maxAge to always automatically expire

### ISSUE THREAD

**Issue by isaacs** [isaacs/node-lru-cache#75]
In https://github.com/isaacs/async-cache/issues/6, @kadishmal uses `0` as the `maxAge` to automatically expire entries.

However, a `maxAge` of `0` is used as just "no maximum age" (so items never expire).

Changing maxAge of 0 to mean "automatically expire" is a **huge** breaking change, in a really subtle way that's bound to bite a lot of people unnecessarily.  So, I'd rather not do that.

However, this module _could_ accept `-1` as a `maxAge` value and use _that_ to mean "automatically expire", which at least provides a workaround.

Patch welcome for this.  Please include docs and test.

**Comment by aychtang** [comment]
I added a related PR for this, there seemed to be a nasty equality checking bug when setting maxAge on an item using .set(k, v, maxAge) where the maxAge value was 0 and there was already a default value passed as an option in the constructor.

Aside from that I wasn't sure about the feature, AFAIK with the current expiration logic it already worked as you described as long as you have a negative maxAge (I'm assuming by automatically expire, you mean the item is immediately stale) so I added a couple of test cases, and updated the readme.
