### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by sheerun** [isaacs/node-lru-cache#77]
Please add changelog at least for major releases.

**Comment by kachkaev** [comment]
I just upgraded from `^5.1.1` to `^6.0.0` and have no clue on what I could break with this 😅 

`CHANGELOG.md` as well as some info on the [releases page](https://github.com/isaacs/node-lru-cache/releases) would be much appreciated 🙏

Examples:
- [styled-components CHANGELOG.md](https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md)
- [styled-components releases page](https://github.com/styled-components/styled-components/releases)

**Comment by existe-deja** [comment]
Changelog is a bit documented on the README file but you could improve the usage of this excellent piece of software by adding a proper changelog. https://semantic-release.gitbook.io/ is one of the tool who can improve your build process a lot.
